In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/todasvendas/vendas_modificado.csv

In [4]:
df = pd.read_csv ('/kaggle/input/todasvendas/vendas_modificado.csv')

In [5]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,"R$ 8,74",4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,"R$ 9,48",2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

Removendo os R$

In [6]:
df["valor"] = df["valor"].str.replace("R$", "", regex=False).str.strip()

Verificando

In [7]:
df[["valor"]].head()

   valor
0  16,87
1   3,25
2   1,63
3   8,74
4   9,48

Estou alterando as , por . ; estou tratando os erros dos valores e transformando eles em apenas duas casas decimais

In [8]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,"8,74",4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,"9,48",2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [9]:
# Substituir "," por ".", tratando entradas inválidas
df["valor"] = df["valor"].str.replace(",", ".", regex=False)

# Verificar se as entradas são válidas e converter para float, com tratamento de erro
df["valor"] = pd.to_numeric(df["valor"], errors='coerce')

# Arredondar para 2 casas decimais, ignorando valores NaN (resultados de conversões inválidas)
df["valor"] = df["valor"].round(2)

verificando denovo

In [10]:
df[["valor"]].head(10)

   valor
0  16.87
1   3.25
2   1.63
3   8.74
4   9.48
5  10.16
6   7.77
7  14.93
8   9.51
9   1.25

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368752 entries, 0 to 368751
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id_da_compra  368752 non-null  int64
 1   data          368752 non-null  object
 2   hora          368752 non-null  object
 3   cliente       368752 non-null  object
 4   produto       368752 non-null  object
 5   valor         368669 non-null  float64
 6   quantidade    368752 non-null  int64
 7   total         365067 non-null  float64
 8   status        368752 non-null  object
 9   cidade        368752 non-null  object
 10  estado        368752 non-null  object
 11  pais          368752 non-null  object
 12  cep           368752 non-null  object
 13  frete         361381 non-null  float64
 14  pagamento     368752 non-null  object
 15  vendedor      365072 non-null  object
 16  marca         368752 non-null  object
dtypes: float64(3), int64(2), object(12)
memory usage: 47.8+ MB

In [12]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [13]:
df[["total"]].head()

    total
0  239.31
1    9.75
2   36.67
3   54.96
4   18.96

In [14]:
df[["frete"]].head()

   frete
0   20.0
1    0.0
2   22.0
3   20.0
4    0.0

In [15]:
df[["hora"]].head(
)

       hora
0  23:35:51
1  09:00:53
2  15:30:28
3  08:41:23
4  13:38:45

Verificar se existe valores nulos

In [16]:
df[['valor', 'quantidade', 'total', 'frete']].isnull().sum()

valor           83
quantidade       0
total         3685
frete         7371
dtype: int64

linhas que estão com os valores nulos

In [17]:
df[df[['valor']].isnull().any(axis=1)]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
394,29431,2019-01-12,14:02:00,THIAGO QUEIROZ DE AGUIAR,Presunto,NaN,15,184.15,Transportando,Volta Redonda,RJ,Brasil,27200-000,19.0,Transferência Bancária,FELIPE HENRIQUE COSTA BARNABE MARAZO,Aurora
7718,53850,2022-08-26,20:18:56,JOÃO QUEIROZ DE AGUIAR,Pasta de Dente,NaN,7,31.91,Pagamento Confirmado,Belo Horizonte,MG,Brasil,30000-000,10.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,Sorriso
12960,47174,2022-10-26,17:09:55,LEVI ANTÔNIO DE SOUZA NETO,Molho de Tomate,NaN,10,35.40,Entregue,São Vicente de Minas,MG,Brasil,37370-000,0.0,Transferência Bancária,PAULO SOUZA RONCETE,Elefante
15553,17975,2021-11-15,21:23:55,SAMUEL MATHEUS DA SILVA,Papel Toalha,NaN,10,34.70,Entregue,Tiradentes,MG,Brasil,36325-000,10.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,Elite
15575,41147,2019-09-12,16:30:35,MICAEL CARDOSO DINIZ,Sal,NaN,4,8.64,Em Transporte,Santo André,SP,Brasil,09000-000,0.0,Transferência Bancária,HENRICO VICTOR ALVES,Cisne
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355903,26209,2018-08-17,14:41:11,KALLEBE HENRIQUE CAÇADOR,Macarrão,NaN,9,28.63,Em Separação,Astolfo Dutra,MG,Brasil,36780-000,10.0,Pix,HENRICO VICTOR ALVES,Renata
355949,16758,2018-03-25,02:34:22,VICTOR SANTOS DA SILVA,Amaciante,NaN,15,110.65,Entregue,Resende Costa,MG,Brasil,36340-000,-10.0,Cartão de Crédito,GABRIEL QUEIROZ DE AGUIAR,Fofo
361106,30157,2018-04-28,12:44:13,GABRIEL JOSÉ SILVA MATIAS,Papel Higiênico,NaN,15,62.10,PC,Duque de Caxias,RJ,Brasil,25000-000,0.0,Pix,FELIPE HENRIQUE COSTA BARNABE MARAZO,Personal
362586,52987,2020-11-19,22:24:50,LUCAS QUEIROZ DE AGUIAR,Sal#$@!,NaN,2,14.24,Em Separação,São Tiago,MG,Brasil,36350-000,9.5,Transferência Bancária,FELIPE HENRIQUE COSTA BARNABE MARAZO,Lebre
363339,20531,2020-02-29,13:05:51,LETICIA SOUZA RONCETE,Óleo de Soja,NaN,8,47.20,Pagamento Confirmado,Magé,RJ,Brasil,25900-000,18.0,Cartão de Crédito,GABRIEL QUEIROZ DE AGUIAR,Liza

Visualizar os CEPs nulos

In [18]:
df[df[['frete']].isnull().any(axis=1)]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
42,1867,2020-09-25,17:57:28,GABRIEL FELIPE DE SOUZA,Pasta de Dente,3.37,14,47.18,Entregue,São João de Meriti,RJ,Brasil,25500-000,NaN,Cartão de Crédito,FELIPE HENRIQUE COSTA BARNABE MARAZO,Sorriso
58,56430,2021-11-10,12:33:05,LEVI SILVA RAMOS,Queijo Mussarela,16.45,7,137.15,Aguardando Pagamento,Cabo Frio,RJ,Brasil,28900-000,NaN,Transferência Bancária,FELIPE HENRIQUE COSTA BARNABE MARAZO,Tirolez
92,37806,2018-03-25,12:17:42,MARCO CUNHA DE OLIVEIRA,Queijo Mussarela,14.60,8,116.80,Entregue,Ubá,MG,Brasil,36500-000,NaN,Pix,FELIPE HENRIQUE COSTA BARNABE MARAZO,Tirolez
123,48590,2021-11-03,14:24:36,HENRICO MALAQUIAS DE SOUZA OLIVEIRA,Condicionador,9.85,3,29.55,Pagamento Confirmado,Muriaé,MG,Brasil,36880-000,NaN,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Dove
136,2780,2018-11-05,14:16:20,GABRIEL PAULO ALVES ALVIM,Papel Higiênico,3.81,12,45.72,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,NaN,Cartão de Crédito,PAULO SOUZA RONCETE,Dualette
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368516,6544,2022-08-27,14:18:53,TIAGO VICTOR ALVES,Amaciante,5.65,5,51.25,Em Separação,Angra dos Reis,RJ,Brasil,23900-000,NaN,Cartão de Crédito,HENRICO VICTOR ALVES,Downy
368569,5985,2021-12-28,16:37:43,MATEUS ANTÔNIO DE DECCO OLIVEIRA,Amaciante,5.38,6,44.28,Em Separação,Mariana,MG,Brasil,35420-000,NaN,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Confort
368573,44348,2018-07-31,21:19:02,LUCAS AUGUSTO NERY SILVA,Detergente,3.13,1,3.13,Aguardando Pagamento,Niterói,RJ,Brasil,24000-000,NaN,Cartão de Crédito,HENRICO VICTOR ALVES,Ypê
368583,18826,2021-02-25,14:53:46,VICTOR MATHEUS DA SILVA,Açúcar,2.83,1,2.83,Em Separação,Rio de Janeiro,RJ,Brasil,20000-000,NaN,Pix,LUCAS VITOR FAÇANHA NEVES,Itamarati
368747,43399,2018-11-02,23:00:58,PEDRO GONÇALVES DONADONI,Água Mineral,1.43,14,39.02,Entregue,Belford Roxo,RJ,Brasil,26100-000,NaN,Transferência Bancária,CARLOS QUEIROZ DE AGUIAR,Minalba

Visualizar as quantidades de vezes que aparecem as cidades

In [19]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [20]:
df.groupby('cidade').size().reset_index(name='quantidade')

                   cidade  quantidade
0          Angra dos Reis        6597
1           Astolfo Dutra        6933
2               Barbacena        6678
3                 Barroso        6247
4            Belford Roxo        6114
5          Belo Horizonte        6441
6                   Bicas        6556
7               Cabo Frio        7233
8                Campinas        6603
9   Campos dos Goytacazes        6569
10               Carandaí        6717
11             Cataguases        6669
12              Congonhas        6615
13   Conselheiro Lafaiete        6585
14  Coronel Xavier Chaves        6623
15        Duque de Caxias        6633
16       Ewbank da Câmara        6322
17              Guarulhos        6765
18               Itaboraí        6585
19           Juiz de Fora        6646
20          Lagoa Dourada        6669
21             Leopoldina        6442
22            Lima Duarte        6751
23                  Macaé        6799
24                   Magé        6445
25                Mariana        6877
26         Matias Barbosa        6567
27                 Muriaé        6546
28                Niterói        6547
29            Nova Iguaçu        6397
30            Ouro Branco        6462
31             Ouro Preto        6662
32                  Palma        6861
33             Petrópolis        6759
34                 Prados        6567
35          Resende Costa        6556
36         Rio de Janeiro        6773
37              Ritápolis        6607
38    Santana do Garambéu        6413
39            Santo André        6512
40          Santos Dumont        6604
41          Simão Pereira        6264
42  São Bernardo do Campo        6506
43            São Gonçalo        6406
44    São José dos Campos        6345
45    São João Nepomuceno        6532
46     São João de Meriti        6791
47       São João del-Rei        6279
48              São Paulo        6479
49              São Tiago        6350
50   São Vicente de Minas        6619
51             Tiradentes        6584
52              Tocantins        6575
53                    Ubá        6419
54                 Viçosa        6764
55          Volta Redonda        6892

Visualizar quais as diferenças dos fretes de Muriaé

In [21]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [22]:
df[df['cidade'].str.lower() == "muriaé"]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
29,10768,2020-01-02,09:20:41,VICTOR MURATORI DUTRA,Óleo de Soja,3.75,10,37.50,Aguardando Pagamento,Muriaé,MG,Brasil,36880-000,0.0,Transferência Bancária,CARLOS QUEIROZ DE AGUIAR,Coamo
123,48590,2021-11-03,14:24:36,HENRICO MALAQUIAS DE SOUZA OLIVEIRA,Condicionador,9.85,3,29.55,Pagamento Confirmado,Muriaé,MG,Brasil,36880-000,NaN,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Dove
166,30963,2021-09-17,17:55:38,VICTOR SANTOS DA SILVA,Condicionador,5.99,10,59.90,Em Transporte,Muriaé,MG,Brasil,36880-000,0.0,Cartão de Crédito,CARLOS QUEIROZ DE AGUIAR,Seda
193,59265,2020-08-14,17:33:53,VICTOR PICANÇO SANTOS FERREIRA SILVA,Pasta de Dente,2.53,15,37.95,Aguardando Pagamento,Muriaé,MG,Brasil,36880-000,0.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Oral-B
212,43198,2021-03-25,07:03:52,HIAN RIBEIRO AMORIM,Manteiga,7.24,9,75.16,Pagamento Confirmado,Muriaé,MG,Brasil,36880-000,10.0,Cartão de Crédito,FELIPE HENRIQUE COSTA BARNABE MARAZO,Qualy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368472,8768,2019-11-29,15:58:00,GABRIEL ASSIS NOGUEIRA SILVA,Sal,1.80,5,19.00,Aguardando Pagamento,Muriaé,MG,Brasil,36880-000,10.0,Boleto,PAULO SOUZA RONCETE,Marinho
368597,26625,2020-10-16,12:33:16,MATHEUS VICTOR ALVES,Açúcar,3.22,3,9.66,Em Separação,Muriaé,MG,Brasil,36880-000,0.0,Transferência Bancária,LUCAS VITOR FAÇANHA NEVES,União
368676,1345,2018-08-17,11:25:03,RÔMULO DA CUNHA TEIXEIRA,Manteiga,9.25,8,84.00,Entregue,Muriaé,MG,Brasil,36880-000,10.0,Cartão de Crédito,GABRIEL QUEIROZ DE AGUIAR,Itambé
368703,8805,2022-10-14,17:58:08,JOÃO LACERDA PORTUGAL DA SILVA,Queijo Mussarela,17.24,7,130.68,Pagamento Confirmado,Muriaé,MG,Brasil,36880-000,10.0,Pix,LUCAS VITOR FAÇANHA NEVES,Porto Alegre
368724,54971,2021-08-12,14:55:12,MATEUS VITOR FAÇANHA NEVES,Pão de Forma,5.59,3,26.77,Entregue,Muriaé,MG,Brasil,36880-000,10.0,Boleto,VICTOR GONÇALVES DONADONI,Wickbold

In [23]:
df_agrupado = df.groupby(['cidade', 'cep']).size().reset_index(name='quantidade')

In [24]:
df_agrupado.head()

           cidade        cep  quantidade
0  Angra dos Reis  23900-000        6471
1  Angra dos Reis   239XXXXX         126
2   Astolfo Dutra  36780-000        6811
3   Astolfo Dutra   3678XXXX         122
4       Barbacena  36200-000        6545

Nota se que os ceps errados, apresentam o xxx no lugar do "0"

In [25]:
df[df['cidade'] == "Muriaé"][['cidade', 'cep']].drop_duplicates()

     cidade        cep
29   Muriaé  36880-000
336  Muriaé   3688XXXX

Corrigir o X por 0 nos CEPs

In [26]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [27]:
df['cep'] = df['cep'].astype(str).str.replace("X", "0", regex=False)

Nota se que corrigiu, porem não adicionou o "-"

In [28]:
df.groupby(['cidade', 'cep']).size().reset_index(name='quantidade')

             cidade        cep  quantidade
0    Angra dos Reis  23900-000        6471
1    Angra dos Reis   23900000         126
2     Astolfo Dutra  36780-000        6811
3     Astolfo Dutra   36780000         122
4         Barbacena  36200-000        6545
..              ...        ...         ...
107             Ubá   36500000         113
108          Viçosa  36570-000        6649
109          Viçosa   36570000         115
110   Volta Redonda  27200-000        6776
111   Volta Redonda   27200000         116

[112 rows x 3 columns]

In [29]:

df['cep'] = df['cep'].astype(str)


df_sem_hifen = df[~df['cep'].str.contains("-", na=False)]


df.loc[df.index.isin(df_sem_hifen.index), 'cep'] = df_sem_hifen['cep'].str[:5] + "-" + df_sem_hifen['cep'].str[5:]

Corrijindo os CEPs com a norma correta e os hifens, além  de garantir que sejam strings

In [30]:
df.groupby(['cidade', 'cep']).size()

cidade                 cep
Angra dos Reis         23900-000    6597
Astolfo Dutra          36780-000    6933
Barbacena              36200-000    6678
Barroso                36212-000    6247
Belford Roxo           26100-000    6114
Belo Horizonte         30000-000    6441
Bicas                  36600-000    6556
Cabo Frio              28900-000    7233
Campinas               13000-000    6603
Campos dos Goytacazes  28000-000    6569
Carandaí               36280-000    6717
Cataguases             36770-000    6669
Congonhas              36415-000    6615
Conselheiro Lafaiete   36400-000    6585
Coronel Xavier Chaves  36330-000    6623
Duque de Caxias        25000-000    6633
Ewbank da Câmara       36108-000    6322
Guarulhos              07000-000    6765
Itaboraí               24800-000    6585
Juiz de Fora           36000-000    6646
Lagoa Dourada          36345-000    6669
Leopoldina             36700-000    6442
Lima Duarte            36140-000    6751
Macaé                  27900-000    6799
Magé                   25900-000    6445
Mariana                35420-000    6877
Matias Barbosa         36120-000    6567
Muriaé                 36880-000    6546
Niterói                24000-000    6547
Nova Iguaçu            26000-000    6397
Ouro Branco            36420-000    6462
Ouro Preto             35400-000    6662
Palma                  36710-000    6861
Petrópolis             25600-000    6759
Prados                 36320-000    6567
Resende Costa          36340-000    6556
Rio de Janeiro         20000-000    6773
Ritápolis              36335-000    6607
Santana do Garambéu    36196-000    6413
Santo André            09000-000    6512
Santos Dumont          36240-000    6604
Simão Pereira          36123-000    6264
São Bernardo do Campo  09700-000    6506
São Gonçalo            24400-000    6406
São José dos Campos    12200-000    6345
São João Nepomuceno    36680-000    6532
São João de Meriti     25500-000    6791
São João del-Rei       36300-000    6279
São Paulo              01000-000    6479
São Tiago              36350-000    6350
São Vicente de Minas   37370-000    6619
Tiradentes             36325-000    6584
Tocantins              36510-000    6575
Ubá                    36500-000    6419
Viçosa                 36570-000    6764
Volta Redonda          27200-000    6892
dtype: int64

In [31]:
df[df['cidade'] == "Muriaé"][['cidade', 'cep']].drop_duplicates()

    cidade        cep
29  Muriaé  36880-000

verifica se existe outros valores alem do correto em Muriaé, por exemplo

In [32]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [33]:
df.isnull().sum()

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor             83
quantidade         0
total           3685
status             0
cidade             0
estado             0
pais               0
cep                0
frete           7371
pagamento          0
vendedor        3680
marca              0
dtype: int64

Verificar quais os dados faltantes

In [34]:
# vou calcular a mediana dos fretes, porem para que isso aconteca eu preciso tratar os dados nulos para zero e não contar-los na mediana:

df['frete'] = df['frete'].fillna(0)

In [35]:
#verificando se ha numeros nulos
df['frete'].isnull().sum()

0

In [36]:
#agora sim, verificar a mediana sem nenhum erro:
mediana_frete_por_cidade = df[df['frete'].notna() & (df['frete'] > 0)].groupby('cidade')['frete'].median().to_dict()

In [37]:
print(f"Mediana do frete (positivos): {mediana_frete_por_cidade}")

Mediana do frete (positivos): {'Angra dos Reis': 23.0, 'Astolfo Dutra': 10.0, 'Barbacena': 12.0, 'Barroso': 8.5, 'Belford Roxo': 19.0, 'Belo Horizonte': 10.0, 'Bicas': 9.0, 'Cabo Frio': 22.0, 'Campinas': 17.0, 'Campos dos Goytacazes': 20.0, 'Carandaí': 9.0, 'Cataguases': 10.5, 'Congonhas': 10.5, 'Conselheiro Lafaiete': 10.5, 'Coronel Xavier Chaves': 11.0, 'Duque de Caxias': 19.0, 'Ewbank da Câmara': 11.0, 'Guarulhos': 18.0, 'Itaboraí': 18.5, 'Juiz de Fora': 13.0, 'Lagoa Dourada': 10.0, 'Leopoldina': 9.5, 'Lima Duarte': 10.0, 'Macaé': 20.0, 'Magé': 18.0, 'Mariana': 12.0, 'Matias Barbosa': 10.0, 'Muriaé': 10.0, 'Niterói': 20.0, 'Nova Iguaçu': 18.0, 'Ouro Branco': 10.0, 'Ouro Preto': 12.5, 'Palma': 9.0, 'Petrópolis': 21.0, 'Prados': 8.0, 'Resende Costa': 10.0, 'Rio de Janeiro': 22.0, 'Ritápolis': 9.0, 'Santana do Garambéu': 8.5, 'Santo André': 18.0, 'Santos Dumont': 11.0, 'Simão Pereira': 9.5, 'São Bernardo do Campo': 18.0, 'São Gonçalo': 20.0, 'São José dos Campos': 17.0, 'São João Nepomuceno': 12.0, 'São João de Meriti': 18.0, 'São João del-Rei': 10.5, 'São Paulo': 20.0, 'São Tiago': 9.5, 'São Vicente de Minas': 12.0, 'Tiradentes': 10.0, 'Tocantins': 8.5, 'Ubá': 11.0, 'Viçosa': 9.0, 'Volta Redonda': 19.0}

In [38]:
# Substituir o valor do frete pela sua mediana:
df['frete'] = df.apply(lambda row: row['frete'] if row['frete'] >= 0 else mediana_frete_por_cidade.get(row['cidade'], row['frete']),axis=1)

mediana_frete_por_cidade = df[df['frete'] > 0].groupby('cidade')['frete'].median().to_dict()

df['frete'] = df.apply(lambda row: mediana_frete_por_cidade.get(row['cidade'], row['frete']) if row['frete'] == 0 else row['frete'],axis=1)

In [39]:
#pronto, sem fretes negativos e zerados
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [40]:
#verificar denovo quais sao os dados nulos:
df.isnull().sum()

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor             83
quantidade         0
total           3685
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor        3680
marca              0
dtype: int64

In [41]:
#vamos tratar o vendedor agr:

# Filtrar apenas as linhas onde o vendedor está nulo
df_vendedor_nulo = df[df['vendedor'].isna()]

# Exibir o resultado
print("Linhas onde o vendedor está nulo:")
display(df_vendedor_nulo)

Linhas onde o vendedor está nulo:

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
112,52388,2018-07-30,07:10:51,MIGUEL ANTÔNIO DE DECCO OLIVEIRA,Manteiga,8.77,5,56.85,Pagamento Confirmado,Juiz de Fora,MG,Brasil,36000-000,13.0,Cartão de Crédito,NaN,Aviação
425,46034,2019-12-28,14:14:40,RAFAEL HENRIQUE COSTA BARNABE MARAZO,Suco de Laranja,825.30,5,31.50,Aguardando Pagamento,Leopoldina,MG,Brasil,36700-000,9.5,Boleto,NaN,Prats
525,30444,2022-09-11,21:39:42,LUCAS GONÇALVES DONADONI,Café,10.33,2,20.66,Em Separação,Niterói,RJ,Brasil,24000-000,20.0,Transferência Bancária,NaN,3 Corações
543,41142,2020-10-16,12:47:08,GABRIEL CARLOS DE SOUZA,Vinho,28.89,1,28.89,Pagamento Confirmado,Coronel Xavier Chaves,MG,Brasil,36330-000,11.0,Cartão de Crédito,NaN,Miolo
544,194,2020-06-28,12:28:55,MATEUS Araujo Kuhn,Suco de Laranja,6.86,6,51.16,Em Separação,Lima Duarte,MG,Brasil,36140-000,10.0,Pix,NaN,Prats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368318,53487,2022-03-16,21:05:23,MARCO RIBEIRO AMORIM,Café,12.54,4,50.16,Aguardando Pagamento,Juiz de Fora,MG,Brasil,36000-000,13.0,Boleto,NaN,Melitta
368505,40433,2018-05-06,19:59:40,VICTOR ASSIS NOGUEIRA SILVA,Sal,1.73,15,25.95,Pagamento Confirmado,Lima Duarte,MG,Brasil,36140-000,10.0,Cartão de Crédito,NaN,Lebre
368532,9752,2020-12-24,15:18:31,SAMUEL ANTÔNIO DE DECCO OLIVEIRA,Suco de Laranja#$@!,4.83,4,19.32,Pagamento Confirmado,Belo Horizonte,MG,Brasil,30000-000,10.0,Boleto,NaN,Prats
368675,48278,2021-04-29,19:40:55,THIAGO MATOS LIMA DA CUNHA,Sabão em Pó,9.04,5,62.20,Em Separação,São José dos Campos,SP,Brasil,12200-000,17.0,Cartão de Crédito,NaN,Tixan
368704,17425,2020-01-02,15:35:08,RÔMULO HENRIQUE CAÇADOR,Farinha de Trigo,2.62,14,36.68,Em Transporte,Tocantins,MG,Brasil,36510-000,8.5,Transferência Bancária,NaN,Dona Benta

In [42]:
df = df.dropna(subset=['vendedor'])

In [43]:
#vamos verificar se ainda ha algum nulo
print(df['vendedor'].isna().sum())

0

In [44]:
#vamos verificar denovo:
df.isnull().sum()

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor             83
quantidade         0
total           3650
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor           0
marca              0
dtype: int64

In [45]:
#vamos visualizar os produtos agora:
produtos_unicos = df['produto'].unique()

# Converter para lista para facilitar a visualização
produtos_unicos_list = produtos_unicos.tolist()

# Exibir todos os produtos
for produto in produtos_unicos_list:
    print(produto)

Queijo Mussarela
Molho de Tomate
Água Mineral
Carvão
Café
Feijão
Condicionador
Sabonete
Açúcar
Manteiga
Papel Higiênico
Óleo de Soja
Vinho
Macarrão
Shampoo
Presunto
Cerveja
Café#$@!
Papel Toalha
Pasta de Dente
Pão de Forma#$@!
Sabão em Pó
Amaciante
Desinfetante
Refrigerante#$@!
Arroz
Farinha de Trigo
Biscoito Recheado
Sal
Suco de Laranja
Leite Integral
Detergente
Pão de Forma
Refrigerante
Açúcar#$@!
Papel Toalha#$@!
Macarrão#$@!
Farinha de Trigo#$@!
Manteiga#$@!
Pasta de Dente#$@!
Queijo Mussarela#$@!
Desinfetante#$@!
Água Mineral#$@!
Molho de Tomate#$@!
Sal#$@!
Presunto#$@!
Sabonete#$@!
Suco de Laranja#$@!
Papel Higiênico#$@!
Amaciante#$@!
Condicionador#$@!
Detergente#$@!
Vinho#$@!
Feijão#$@!
Biscoito Recheado#$@!
Cerveja#$@!
Shampoo#$@!
Óleo de Soja#$@!
Leite Integral#$@!
Sabão em Pó#$@!
Arroz#$@!
Refrigkrante
Carvão#$@!
Scl
Papel qoalha
Desinfetanue
Qbeijo Mussarela
Água Mineras
Presuntd
Macawrão
Sucoyde Laranja
Clfé
Desinfekante
Majarrão
Cnfé
Farinha de Tripo
Manteigt
zabonete
Mqcarrão
Arroc
tal
Sabonepe
Papel Twalha
Água Mineual
Condicioiador#$@!
Condibionador
Caft
ieijão
Açúcaz
Amaciayte
Caff
Mopho de Tomate
Molmo de Tomate
Macirrão
Deqergente
Cafc
Queijo Mussarelz
Deterwente

In [46]:
#vimos produtos escrito errado e vamos tratar:
df['produto'] = df['produto'].str.replace('#$@!', '', regex=False)

In [47]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [48]:
#visualizar novamente:
produtos_unicos = df['produto'].unique()
produtos_unicos_list = produtos_unicos.tolist()
for produto in produtos_unicos_list:
    print(produto)

Queijo Mussarela
Molho de Tomate
Água Mineral
Carvão
Café
Feijão
Condicionador
Sabonete
Açúcar
Manteiga
Papel Higiênico
Óleo de Soja
Vinho
Macarrão
Shampoo
Presunto
Cerveja
Papel Toalha
Pasta de Dente
Pão de Forma
Sabão em Pó
Amaciante
Desinfetante
Refrigerante
Arroz
Farinha de Trigo
Biscoito Recheado
Sal
Suco de Laranja
Leite Integral
Detergente
Refrigkrante
Scl
Papel qoalha
Desinfetanue
Qbeijo Mussarela
Água Mineras
Presuntd
Macawrão
Sucoyde Laranja
Clfé
Desinfekante
Majarrão
Cnfé
Farinha de Tripo
Manteigt
zabonete
Mqcarrão
Arroc
tal
Sabonepe
Papel Twalha
Água Mineual
Condicioiador
Condibionador
Caft
ieijão
Açúcaz
Amaciayte
Caff
Mopho de Tomate
Molmo de Tomate
Macirrão
Deqergente
Cafc
Queijo Mussarelz
Deterwente

In [49]:
#vamos tratar essas escritas erradas
def padronizar_produto(produto):
    mapping = {
        'Qbeijo Mussarela': 'Queijo Mussarela',
        'Queijo Mussarelz': 'Queijo Mussarela',
        'Mopho de Tomate': 'Molho de Tomate',
        'Molmo de Tomate': 'Molho de Tomate',
        'Água Mineras': 'Água Mineral',
        'Água Minera': 'Água Mineral',
        'Clfé': 'Café',
        'Cnfé': 'Café',
        'Caft': 'Café',
        'Caff': 'Café',
        'Cafc': 'Café',
        'ieijão': 'Feijão',
        'Scl': 'Sal',
        'tal': 'Sal',
        'Sabonepe': 'Sabonete',
        'Refrigkrante': 'Refrigerante',
        'Papel qoalha': 'Papel Toalha',
        'Papel Twalha': 'Papel Toalha',
        'Desinfetanue': 'Desinfetante',
        'Desinfekante': 'Desinfetante',
        'Presuntd': 'Presunto',
        'Sucoyde Laranja': 'Suco de Laranja',
        'Manteigt': 'Manteiga',
        'Mqcarrão': 'Macirrão',
        'Condicioiador': 'Condicionador',
        'Condibionador': 'Condicionador',
        'Sabonepe': 'Sabonete',
        'Macirrão': 'Macarrão',
        'Mqcarrão': 'Macarrão',
        'Macawrão': 'Macarrão',
        'Majarrão': 'Macarrão',
        'Farinha de Tripo': 'Farinha de Trigo',
        'Açúcaz': 'Açúcar',
        'zabonete': 'Sabonete',
        'Arroc': 'Arroz',
        'Amaciayte': 'Amaciante',
        'Biscoitq Recheado': 'Biscoito Recheado',
        'Deqergente': 'Detergente',
        'Deterwente': 'Detergente',
        'Água Mineual': 'Água Mineral',
    }
    if pd.isnull(produto):
        return produto
    return mapping.get(produto, produto)
df['produto'] = df['produto'].apply(padronizar_produto)

In [50]:
#visualizar novamente:
produtos_unicos = df['produto'].unique()
produtos_unicos_list = produtos_unicos.tolist()
for produto in produtos_unicos_list:
    print(produto)

Queijo Mussarela
Molho de Tomate
Água Mineral
Carvão
Café
Feijão
Condicionador
Sabonete
Açúcar
Manteiga
Papel Higiênico
Óleo de Soja
Vinho
Macarrão
Shampoo
Presunto
Cerveja
Papel Toalha
Pasta de Dente
Pão de Forma
Sabão em Pó
Amaciante
Desinfetante
Refrigerante
Arroz
Farinha de Trigo
Biscoito Recheado
Sal
Suco de Laranja
Leite Integral
Detergente

In [51]:
df.head(10)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações
5,38623,2018-02-19,17:32:01,LUCAS ANTÔNIO DE SOUZA NETO,Café,10.16,1,20.16,Entregue com Sucesso,Resende Costa,MG,Brasil,36340-000,10.0,Transferência Bancária,VICTOR GONÇALVES DONADONI,3 Corações
6,46627,2018-04-21,22:08:30,GUILHERME IVAIR DE ASSIS SETTA,Feijão,7.77,3,43.31,Em Separação,São Paulo,SP,Brasil,01000-000,20.0,Pix,SAMUEL HENRIQUE CAÇADOR,Caldo Bom
7,53579,2020-09-25,12:04:15,GABRIEL MUZY FERNANDES,Queijo Mussarela,14.93,14,218.02,Em Separação,Bicas,MG,Brasil,36600-000,9.0,Boleto,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Porto Alegre
8,34924,2018-06-20,17:10:42,LEVI MATOS LIMA DA CUNHA,Condicionador,9.51,5,69.55,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Pix,FELIPE HENRIQUE COSTA BARNABE MARAZO,Pantene
9,10575,2018-10-01,18:36:45,HENRICO DA CUNHA TEIXEIRA,Sabonete,1.25,2,13.00,Em Separação,São João del-Rei,MG,Brasil,36300-000,10.5,Boleto,GABRIEL QUEIROZ DE AGUIAR,Dove

In [52]:
df.isnull().sum()

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor             83
quantidade         0
total           3650
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor           0
marca              0
dtype: int64

In [53]:
#vamos ver os valores nulos
print(df[df['valor'].isnull()])

        id_da_compra        data      hora                     cliente  \
394            29431  2019-01-12  14:02:00    THIAGO QUEIROZ DE AGUIAR
7718           53850  2022-08-26  20:18:56      JOÃO QUEIROZ DE AGUIAR
12960          47174  2022-10-26  17:09:55  LEVI ANTÔNIO DE SOUZA NETO
15553          17975  2021-11-15  21:23:55     SAMUEL MATHEUS DA SILVA
15575          41147  2019-09-12  16:30:35        MICAEL CARDOSO DINIZ
...              ...         ...       ...                         ...
355903         26209  2018-08-17  14:41:11    KALLEBE HENRIQUE CAÇADOR
355949         16758  2018-03-25  02:34:22      VICTOR SANTOS DA SILVA
361106         30157  2018-04-28  12:44:13   GABRIEL JOSÉ SILVA MATIAS
362586         52987  2020-11-19  22:24:50     LUCAS QUEIROZ DE AGUIAR
363339         20531  2020-02-29  13:05:51       LETICIA SOUZA RONCETE

                produto  valor  quantidade   total                status  \
394            Presunto    NaN          15  184.15         Transportando
7718     Pasta de Dente    NaN           7   31.91  Pagamento Confirmado
12960   Molho de Tomate    NaN          10   35.40              Entregue
15553      Papel Toalha    NaN          10   34.70              Entregue
15575               Sal    NaN           4    8.64         Em Transporte
...                 ...    ...         ...     ...                   ...
355903         Macarrão    NaN           9   28.63          Em Separação
355949        Amaciante    NaN          15  110.65              Entregue
361106  Papel Higiênico    NaN          15   62.10                    PC
362586              Sal    NaN           2   14.24          Em Separação
363339     Óleo de Soja    NaN           8   47.20  Pagamento Confirmado

                      cidade estado    pais        cep  frete  \
394            Volta Redonda     RJ  Brasil  27200-000   19.0
7718          Belo Horizonte     MG  Brasil  30000-000   10.0
12960   São Vicente de Minas     MG  Brasil  37370-000   12.0
15553             Tiradentes     MG  Brasil  36325-000   10.0
15575            Santo André     SP  Brasil  09000-000   18.0
...                      ...    ...     ...        ...    ...
355903         Astolfo Dutra     MG  Brasil  36780-000   10.0
355949         Resende Costa     MG  Brasil  36340-000   10.0
361106       Duque de Caxias     RJ  Brasil  25000-000   19.0
362586             São Tiago     MG  Brasil  36350-000    9.5
363339                  Magé     RJ  Brasil  25900-000   18.0

                     pagamento                              vendedor     marca
394     Transferência Bancária  FELIPE HENRIQUE COSTA BARNABE MARAZO    Aurora
7718         Cartão de Crédito           HENRICO MATOS LIMA DA CUNHA   Sorriso
12960   Transferência Bancária                   PAULO SOUZA RONCETE  Elefante
15553        Cartão de Crédito           HENRICO MATOS LIMA DA CUNHA     Elite
15575   Transferência Bancária                  HENRICO VICTOR ALVES     Cisne
...                        ...                                   ...       ...
355903                     Pix                  HENRICO VICTOR ALVES    Renata
355949       Cartão de Crédito             GABRIEL QUEIROZ DE AGUIAR      Fofo
361106                     Pix  FELIPE HENRIQUE COSTA BARNABE MARAZO  Personal
362586  Transferência Bancária  FELIPE HENRIQUE COSTA BARNABE MARAZO     Lebre
363339       Cartão de Crédito             GABRIEL QUEIROZ DE AGUIAR      Liza

[83 rows x 17 columns]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [54]:
#vamos verificar se ha valores nulos nas colunas valor e total, caso nao haja, preciso apenas realizar equacoes que descobrem o valor faltante:

# Verifica se há linhas onde 'valor' e 'total' estão nulos
instancias_vazias = df[df['valor'].isnull() & df['total'].isnull()]

# Exibe o resultado
print(instancias_vazias)

# exibir o numero de instancias
print(instancias_vazias.shape[0])

        id_da_compra        data      hora                            cliente  \
273587          2782  2022-10-09  06:16:11  Breno MALAQUIAS DE SOUZA OLIVEIRA

               produto  valor  quantidade  total                status  \
273587  Leite Integral    NaN           8    NaN  Aguardando Pagamento

               cidade estado    pais        cep  frete  \
273587  Santos Dumont     MG  Brasil  36240-000   11.0

                     pagamento                 vendedor  marca
273587  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR  Elegê
1

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [55]:
df.loc[df['total'].isnull(), 'total'] = df['quantidade'] * df['valor']
df.loc[df['total'].isnull(), 'total'] = (df['quantidade'] * df['valor']) + df['frete']

In [56]:
df.isnull().sum()

id_da_compra     0
data             0
hora             0
cliente          0
produto          0
valor           83
quantidade       0
total            1
status           0
cidade           0
estado           0
pais             0
cep              0
frete            0
pagamento        0
vendedor         0
marca            0
dtype: int64

In [57]:
#vamos ver o unico total nulo

# Verifica se há linhas onde 'valor' e 'total' estão nulos
instancias_vazias = df[df['valor'].isnull() & df['total'].isnull()]

# Exibe o resultado
print(instancias_vazias)

# exibir o numero de instancias
print(instancias_vazias.shape[0])

        id_da_compra        data      hora                            cliente  \
273587          2782  2022-10-09  06:16:11  Breno MALAQUIAS DE SOUZA OLIVEIRA

               produto  valor  quantidade  total                status  \
273587  Leite Integral    NaN           8    NaN  Aguardando Pagamento

               cidade estado    pais        cep  frete  \
273587  Santos Dumont     MG  Brasil  36240-000   11.0

                     pagamento                 vendedor  marca
273587  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR  Elegê
1

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [58]:
#visto que o unico valor do total vazio eh o valor do leite, vamos procurar outras vezes em que ele aparece pra descobrir o seu valor

print(df[df['produto'] == 'Leite Integral'][['produto', 'valor']])

               produto   valor
80      Leite Integral    3.25
119     Leite Integral    4.26
131     Leite Integral    4.06
165     Leite Integral    4.34
218     Leite Integral  505.66
...                ...     ...
368636  Leite Integral    4.25
368653  Leite Integral    4.54
368655  Leite Integral    3.87
368710  Leite Integral    3.84
368741  Leite Integral    3.34

[4690 rows x 2 columns]

In [59]:
# Filtra só o produto "Leite Integral" e remove valores nulos
leite = df[(df['produto'] == 'Leite Integral') & (df['valor'].notnull())]

# Calcula o IQR (intervalo interquartil)
q1 = leite['valor'].quantile(0.25)
q3 = leite['valor'].quantile(0.75)
iqr = q3 - q1

# Define limites inferior e superior para detectar outliers
limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

# Remove os valores fora do intervalo (outliers)
leite_sem_outliers = leite[(leite['valor'] >= limite_inferior) & (leite['valor'] <= limite_superior)]

# Calcula a mediana final
mediana_limpa = leite_sem_outliers['valor'].median()
print(f"Mediana do 'Leite Integral' sem valores discrepantes: {mediana_limpa}")

Mediana do 'Leite Integral' sem valores discrepantes: 3.98

In [60]:
#agora vamos adicionar esse valor ao valor do leite integral:
# Localiza a linha onde o produto é "Leite Integral" e valor/total estão nulos
filtro = (df['produto'] == 'Leite Integral') & (df['valor'].isnull()) & (df['total'].isnull())

# Atribui a mediana à coluna 'valor' dessa linha
df.loc[filtro, 'valor'] = mediana_limpa

In [61]:
#vamos verificar:
print(df.loc[filtro])

        id_da_compra        data      hora                            cliente  \
273587          2782  2022-10-09  06:16:11  Breno MALAQUIAS DE SOUZA OLIVEIRA

               produto  valor  quantidade  total                status  \
273587  Leite Integral   3.98           8    NaN  Aguardando Pagamento

               cidade estado    pais        cep  frete  \
273587  Santos Dumont     MG  Brasil  36240-000   11.0

                     pagamento                 vendedor  marca
273587  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR  Elegê

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [62]:
print(df.loc[filtro])

        id_da_compra        data      hora                            cliente  \
273587          2782  2022-10-09  06:16:11  Breno MALAQUIAS DE SOUZA OLIVEIRA

               produto  valor  quantidade  total                status  \
273587  Leite Integral   3.98           8    NaN  Aguardando Pagamento

               cidade estado    pais        cep  frete  \
273587  Santos Dumont     MG  Brasil  36240-000   11.0

                     pagamento                 vendedor  marca
273587  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR  Elegê

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [63]:
quantidade_vazios = df['valor'].isnull().sum()
print(f"Quantidade de valores vazios na coluna 'valor': {quantidade_vazios}")

Quantidade de valores vazios na coluna 'valor': 82

In [64]:
# Filtra apenas as linhas onde 'valor' está nulo e as outras colunas necessárias estão preenchidas
filtro = df['valor'].isnull() & df['total'].notnull() & df['frete'].notnull() & df['quantidade'].notnull()

# Aplica a fórmula para calcular o valor unitário
df.loc[filtro, 'valor'] = (df.loc[filtro, 'total'] - df.loc[filtro, 'frete']) / df.loc[filtro, 'quantidade']

In [65]:
print(df.loc[filtro])

        id_da_compra        data      hora                     cliente  \
394            29431  2019-01-12  14:02:00    THIAGO QUEIROZ DE AGUIAR
7718           53850  2022-08-26  20:18:56      JOÃO QUEIROZ DE AGUIAR
12960          47174  2022-10-26  17:09:55  LEVI ANTÔNIO DE SOUZA NETO
15553          17975  2021-11-15  21:23:55     SAMUEL MATHEUS DA SILVA
15575          41147  2019-09-12  16:30:35        MICAEL CARDOSO DINIZ
...              ...         ...       ...                         ...
355903         26209  2018-08-17  14:41:11    KALLEBE HENRIQUE CAÇADOR
355949         16758  2018-03-25  02:34:22      VICTOR SANTOS DA SILVA
361106         30157  2018-04-28  12:44:13   GABRIEL JOSÉ SILVA MATIAS
362586         52987  2020-11-19  22:24:50     LUCAS QUEIROZ DE AGUIAR
363339         20531  2020-02-29  13:05:51       LETICIA SOUZA RONCETE

                produto      valor  quantidade   total                status  \
394            Presunto  11.010000          15  184.15         Transportando
7718     Pasta de Dente   3.130000           7   31.91  Pagamento Confirmado
12960   Molho de Tomate   2.340000          10   35.40              Entregue
15553      Papel Toalha   2.470000          10   34.70              Entregue
15575               Sal  -2.340000           4    8.64         Em Transporte
...                 ...        ...         ...     ...                   ...
355903         Macarrão   2.070000           9   28.63          Em Separação
355949        Amaciante   6.710000          15  110.65              Entregue
361106  Papel Higiênico   2.873333          15   62.10                    PC
362586              Sal   2.370000           2   14.24          Em Separação
363339     Óleo de Soja   3.650000           8   47.20  Pagamento Confirmado

                      cidade estado    pais        cep  frete  \
394            Volta Redonda     RJ  Brasil  27200-000   19.0
7718          Belo Horizonte     MG  Brasil  30000-000   10.0
12960   São Vicente de Minas     MG  Brasil  37370-000   12.0
15553             Tiradentes     MG  Brasil  36325-000   10.0
15575            Santo André     SP  Brasil  09000-000   18.0
...                      ...    ...     ...        ...    ...
355903         Astolfo Dutra     MG  Brasil  36780-000   10.0
355949         Resende Costa     MG  Brasil  36340-000   10.0
361106       Duque de Caxias     RJ  Brasil  25000-000   19.0
362586             São Tiago     MG  Brasil  36350-000    9.5
363339                  Magé     RJ  Brasil  25900-000   18.0

                     pagamento                              vendedor     marca
394     Transferência Bancária  FELIPE HENRIQUE COSTA BARNABE MARAZO    Aurora
7718         Cartão de Crédito           HENRICO MATOS LIMA DA CUNHA   Sorriso
12960   Transferência Bancária                   PAULO SOUZA RONCETE  Elefante
15553        Cartão de Crédito           HENRICO MATOS LIMA DA CUNHA     Elite
15575   Transferência Bancária                  HENRICO VICTOR ALVES     Cisne
...                        ...                                   ...       ...
355903                     Pix                  HENRICO VICTOR ALVES    Renata
355949       Cartão de Crédito             GABRIEL QUEIROZ DE AGUIAR      Fofo
361106                     Pix  FELIPE HENRIQUE COSTA BARNABE MARAZO  Personal
362586  Transferência Bancária  FELIPE HENRIQUE COSTA BARNABE MARAZO     Lebre
363339       Cartão de Crédito             GABRIEL QUEIROZ DE AGUIAR      Liza

[82 rows x 17 columns]

In [66]:
#vou verificar se ha algum valor negativo nos campos
print(f"Quantidade de valores negativos em 'valor': {(df['valor'] < 0).sum()}")
print(f"Quantidade de valores negativos em 'frete': {(df['frete'] < 0).sum()}")
print(f"Quantidade de valores negativos em 'total': {(df['total'] < 0).sum()}")

Quantidade de valores negativos em 'valor': 11
Quantidade de valores negativos em 'frete': 0
Quantidade de valores negativos em 'total': 0

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)

In [67]:
#preciso alterar os valores negativos do campo valor
# Itera sobre os produtos com valores negativos
produtos_com_erro = df[df['valor'] < 0]['produto'].unique()

for produto in produtos_com_erro:
    # Calcula a mediana sem valores negativos ou extremos
    valores_validos = df[(df['produto'] == produto) & (df['valor'] > 0)]
    mediana = valores_validos['valor'].median()

    # Substitui os negativos pela mediana
    df.loc[(df['produto'] == produto) & (df['valor'] < 0), 'valor'] = mediana

In [68]:
#verificar se alterou mesmo

print(f"Quantidade de valores negativos em 'valor': {(df['valor'] < 0).sum()}")
print(f"Quantidade de valores negativos em 'frete': {(df['frete'] < 0).sum()}")
print(f"Quantidade de valores negativos em 'total': {(df['total'] < 0).sum()}")

Quantidade de valores negativos em 'valor': 0
Quantidade de valores negativos em 'frete': 0
Quantidade de valores negativos em 'total': 0

/usr/local/lib/python3.10/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)

In [69]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações

In [70]:
#vamos ver se existe outliers
# Calcula os quartis
q1 = df['valor'].quantile(0.25)
q3 = df['valor'].quantile(0.75)
iqr = q3 - q1

# Define os limites inferiores e superiores
limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

# Filtra os valores discrepantes (fora do intervalo)
outliers = df[(df['valor'] < limite_inferior) | (df['valor'] > limite_superior)]

# Visualiza os valores discrepantes
print(outliers)

        id_da_compra        data      hora                            cliente  \
23              7912  2021-03-22  06:45:54           MATHEUS SILVINO DA SILVA
35             43002  2021-01-20  15:11:26          FELIPE DA SILVA BIANQUINI
62             11256  2022-10-25  17:56:19            LUCAS BRENO PRADO SILVA
64             56909  2018-08-22  22:48:35               MARCO RIBEIRO AMORIM
99             21247  2022-01-20  16:06:33              MARCO SANTOS DA SILVA
...              ...         ...       ...                                ...
368663         21327  2022-07-15  07:20:22  MATHEUS LACERDA PORTUGAL DA SILVA
368703          8805  2022-10-14  17:58:08     JOÃO LACERDA PORTUGAL DA SILVA
368731         47461  2019-06-01  07:53:51              SAMUEL MUZY FERNANDES
368735         40352  2019-04-22  23:12:31              VICTOR RIBAS DE MOURA
368748         18398  2022-08-13  12:46:43               PEDRO MURATORI DUTRA

                 produto    valor  quantidade   total                status  \
23                 Vinho    30.35           3   99.55  Aguardando Pagamento
35                 Vinho    33.33           6  219.98  Aguardando Pagamento
62                 Vinho    23.89           7  167.23  Aguardando Pagamento
64                 Arroz   586.88           6   26.88  Aguardando Pagamento
99              Macarrão   454.57          13   55.11  Aguardando Pagamento
...                  ...      ...         ...     ...                   ...
368663        Detergente   480.77          15   55.05         Em Transporte
368703  Queijo Mussarela    17.24           7  130.68  Pagamento Confirmado
368731   Suco de Laranja   989.05           1    7.55              Entregue
368735  Queijo Mussarela  2022.64          11  180.34  Pagamento Confirmado
368748      Refrigerante   682.51           4   40.84  Aguardando Pagamento

                       cidade estado    pais        cep  frete  \
23                    Barroso     MG  Brasil  36212-000    8.5
35      Campos dos Goytacazes     RJ  Brasil  28000-000   20.0
62                 Cataguases     MG  Brasil  36770-000   10.5
64        Santana do Garambéu     MG  Brasil  36196-000    8.5
99              Lagoa Dourada     MG  Brasil  36345-000   10.0
...                       ...    ...     ...        ...    ...
368663          Santos Dumont     MG  Brasil  36240-000   11.0
368703                 Muriaé     MG  Brasil  36880-000   10.0
368731             Tiradentes     MG  Brasil  36325-000   10.0
368735              Congonhas     MG  Brasil  36415-000   10.5
368748            São Gonçalo     RJ  Brasil  24400-000   20.0

                     pagamento                              vendedor  \
23           Cartão de Crédito             LUCAS VITOR FAÇANHA NEVES
35       Pagamento Instantâneo              CARLOS QUEIROZ DE AGUIAR
62      Transferência Bancária              CARLOS QUEIROZ DE AGUIAR
64                      Boleto  FELIPE HENRIQUE COSTA BARNABE MARAZO
99           Cartão de Crédito    MICAEL MALAQUIAS DE SOUZA OLIVEIRA
...                        ...                                   ...
368663  Transferência Bancária    MICAEL MALAQUIAS DE SOUZA OLIVEIRA
368703                     Pix             LUCAS VITOR FAÇANHA NEVES
368731       Cartão de Crédito                  HENRICO VICTOR ALVES
368735                     Pix             VICTOR GONÇALVES DONADONI
368748                     Pix                   PAULO SOUZA RONCETE

                    marca
23                 Salton
35                  Miolo
62          Concha y Toro
64                 Urbano
99                  Adria
...                   ...
368663                Ypê
368703       Porto Alegre
368731              Prats
368735       Porto Alegre
368748  Guaraná Antártica

[20193 rows x 17 columns]

In [71]:
#vamos verificar denovo se esta tudo correto com os valores
# Função para contar casas decimais
def tem_mais_de_duas_casas(valor):
    if pd.isnull(valor):
        return False
    return round(valor, 2) != valor

# Verifica cada coluna
for coluna in ['valor', 'frete', 'total']:
    fora_do_padrao = df[df[coluna].apply(tem_mais_de_duas_casas)]
    print(f"\nValores fora do padrão (mais de 2 casas decimais) na coluna '{coluna}':")
    print(fora_do_padrao[[coluna]])

Valores fora do padrão (mais de 2 casas decimais) na coluna 'valor':
            valor
31026    6.324286
31176    8.940000
33643    2.210000
36322    3.026667
36540    9.976154
43352   34.925000
75532    1.843333
76168    2.620000
93702    3.400000
127692   1.660000
154034   7.170000
158877   2.290000
175199   2.100769
177426   3.550000
183421   1.490000
185948   0.933333
192110   3.110000
200015  10.560000
200680   3.556667
219007   2.830000
223301   6.011429
243573   1.130000
248456   1.158571
250235  13.957500
250947   0.120000
259392   2.695556
260525  23.936667
295340   7.600909
296004   2.130000
311083   2.490000
341822   1.143333
349995   5.860000
350469   1.920000
351728   9.045714
352956   5.850000
354444   4.085385
361106   2.873333
363339   3.650000

Valores fora do padrão (mais de 2 casas decimais) na coluna 'frete':
Empty DataFrame
Columns: [frete]
Index: []

Valores fora do padrão (mais de 2 casas decimais) na coluna 'total':
         total
22      134.52
24       34.38
58      137.15
62      167.23
64       26.88
...        ...
368718   16.30
368719   70.24
368732    6.72
368736   82.48
368738   36.62

[26711 rows x 1 columns]

In [72]:
#vamos converter esses valores errados
df['valor'] = df['valor'].round(2)
df['valor_formatado'] = df['valor'].map(lambda x: f"{x:.2f}")

In [73]:
#vamos verificar denovo se esta tudo correto com os valores
# Função para contar casas decimais
def tem_mais_de_duas_casas(valor):
    if pd.isnull(valor):
        return False
    return round(valor, 2) != valor

# Verifica cada coluna
for coluna in ['valor', 'frete', 'total']:
    fora_do_padrao = df[df[coluna].apply(tem_mais_de_duas_casas)]
    print(f"\nValores fora do padrão (mais de 2 casas decimais) na coluna '{coluna}':")
    print(fora_do_padrao[[coluna]])

Valores fora do padrão (mais de 2 casas decimais) na coluna 'valor':
Empty DataFrame
Columns: [valor]
Index: []

Valores fora do padrão (mais de 2 casas decimais) na coluna 'frete':
Empty DataFrame
Columns: [frete]
Index: []

Valores fora do padrão (mais de 2 casas decimais) na coluna 'total':
         total
22      134.52
24       34.38
58      137.15
62      167.23
64       26.88
...        ...
368718   16.30
368719   70.24
368732    6.72
368736   82.48
368738   36.62

[26711 rows x 1 columns]

In [74]:
#vamos conferir denovo
print(df['valor'])

0          16.87
1           3.25
2           1.63
3           8.74
4           9.48
           ...
368747      1.43
368748    682.51
368749     11.01
368750      4.56
368751      3.17
Name: valor, Length: 365072, dtype: float64

In [75]:
df.isnull().sum()

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor              0
quantidade         0
total              1
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor           0
marca              0
valor_formatado    0
dtype: int64

In [76]:
print(df[df['total'].isnull()])

        id_da_compra        data      hora                            cliente  \
273587          2782  2022-10-09  06:16:11  Breno MALAQUIAS DE SOUZA OLIVEIRA

               produto  valor  quantidade  total                status  \
273587  Leite Integral   3.98           8    NaN  Aguardando Pagamento

               cidade estado    pais        cep  frete  \
273587  Santos Dumont     MG  Brasil  36240-000   11.0

                     pagamento                 vendedor  marca valor_formatado
273587  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR  Elegê            3.98

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

In [77]:
#vamos tratar esse valor nulo no total
# Filtra as instâncias onde o 'total' é nulo
filtro_total_nulo = df['total'].isnull()

# Calcula o 'total' apenas nessas instâncias
df.loc[filtro_total_nulo, 'total'] = (df.loc[filtro_total_nulo, 'valor'] * df.loc[filtro_total_nulo, 'quantidade']) + df.loc[filtro_total_nulo, 'frete']

In [78]:
print(df[df['total'].isnull()])

Empty DataFrame
Columns: [id_da_compra, data, hora, cliente, produto, valor, quantidade, total, status, cidade, estado, pais, cep, frete, pagamento, vendedor, marca, valor_formatado]
Index: []

In [79]:
#vou visualizar se houve a alteracao corretamente
print(df[df['id_da_compra'] == 2782])

        id_da_compra        data      hora  \
7378            2782  2022-10-09  06:16:11
43699           2782  2022-10-09  06:16:11
48302           2782  2022-10-09  06:16:11
254634          2782  2022-10-09  06:16:11
273587          2782  2022-10-09  06:16:11
282270          2782  2022-10-09  06:16:11
324531          2782  2022-10-09  06:16:11

                                     cliente            produto  valor  \
7378       Breno MALAQUIAS DE SOUZA OLIVEIRA  Biscoito Recheado   3.67
43699      Breno MALAQUIAS DE SOUZA OLIVEIRA               Café  11.18
48302      Breno MALAQUIAS DE SOUZA OLIVEIRA  Biscoito Recheado   3.45
254634   Breno MALAQUIAS DE SOUZA OLIVEIRA      Suco de Laranja   5.37
273587     Breno MALAQUIAS DE SOUZA OLIVEIRA     Leite Integral   3.98
282270     Breno MALAQUIAS DE SOUZA OLIVEIRA             Açúcar   2.50
324531     Breno MALAQUIAS DE SOUZA OLIVEIRA               Café   4.50

        quantidade  total                status         cidade estado    pais  \
7378             5  29.35  Aguardando Pagamento  Santos Dumont     MG  Brasil
43699            4  44.72  Aguardando Pagamento  Santos Dumont     MG  Brasil
48302           13  55.85  Aguardando Pagamento  Santos Dumont     MG  Brasil
254634           8  53.96  Aguardando Pagamento  Santos Dumont     MG  Brasil
273587           8  42.84  Aguardando Pagamento  Santos Dumont     MG  Brasil
282270           2  16.00  Aguardando Pagamento  Santos Dumont     MG  Brasil
324531           2  20.00  Aguardando Pagamento  Santos Dumont     MG  Brasil

              cep   frete               pagamento                 vendedor  \
7378    36240-000  7755.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR
43699   36240-000    11.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR
48302   36240-000    11.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR
254634  36240-000    11.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR
273587  36240-000    11.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR
282270  36240-000    11.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR
324531  36240-000    11.0  Transferência Bancária  SAMUEL HENRIQUE CAÇADOR

            marca valor_formatado
7378     Bauducco            3.67
43699       Pilão           11.18
48302    Bauducco            3.45
254634      Prats            5.37
273587      Elegê            3.98
282270  Itamarati            2.50
324531    Melitta            4.50

In [80]:
print(df.iloc[273587])

id_da_compra                            21979
data                               2018-08-26
hora                                 02:36:55
cliente            GABRIEL AUGUSTO NERY SILVA
produto                                Açúcar
valor                                     2.9
quantidade                                  2
total                                     5.8
status                   Pagamento Confirmado
cidade                                   Magé
estado                                     RJ
pais                                   Brasil
cep                                 25900-000
frete                                    18.0
pagamento              Transferência Bancária
vendedor              SAMUEL HENRIQUE CAÇADOR
marca                                   União
valor_formatado                          2.90
Name: 276331, dtype: object

In [81]:
#vmaos verificar quantas id da compra duplicadas
# Conta quantas duplicatas existem na coluna 'id_da_compra'
duplicadas_count = df.duplicated('id_da_compra', keep=False).sum()

# Exibe o número de duplicatas
print(f"Quantidade de duplicatas no 'id_da_compra': {duplicadas_count}")

Quantidade de duplicatas no 'id_da_compra': 365023

In [82]:
#vamos verificar os id de compra iguais em horarios e dias diferentes
# Identifica os duplicados no 'id_da_compra'
duplicados_id = df[df.duplicated('id_da_compra', keep=False)]

# Verifica onde as combinações de 'data' e 'hora' não são duplicadas
duplicados_data_hora_diferente = duplicados_id[~duplicados_id.duplicated(subset=['data', 'hora'], keep=False)]

# Exibe os IDs de compra com data e hora diferentes
print(duplicados_data_hora_diferente[['id_da_compra', 'data', 'hora']])

Empty DataFrame
Columns: [id_da_compra, data, hora]
Index: []

In [83]:
# Salva o arquivo no diretório de trabalho atual no Kaggle
df.to_csv('/kaggle/working/vendas_modificado2.csv', index=False)

# Exibe a confirmação
print("Arquivo CSV atualizado com sucesso!")

Arquivo CSV atualizado com sucesso!

In [84]:
# Verifica o número de valores nulos em cada coluna
valores_faltantes_por_coluna = df.isnull().sum()

# Exibe o total de valores faltantes por coluna
print(valores_faltantes_por_coluna)

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor              0
quantidade         0
total              0
status             0
cidade             0
estado             0
pais               0
cep                0
frete              0
pagamento          0
vendedor           0
marca              0
valor_formatado    0
dtype: int64

In [85]:
df.loc[df['total'].isnull(), 'total'] = (df['quantidade'] * df['valor']) + df['frete']

In [86]:
# Remove espaços antes e depois em todas as colunas de tipo string
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Remove espaços extras entre palavras
df = df.apply(lambda x: x.str.replace(r'\s+', ' ', regex=True) if x.dtype == "object" else x)

print(df.head())

   id_da_compra        data      hora                      cliente  \
0         13679  2021-03-20  23:35:51            LUCAS Araujo Kuhn
1         28070  2020-10-30  09:00:53         MICAEL SOUZA RONCETE
2         47484  2021-06-09  15:30:28    FELIPE AUGUSTO NERY SILVA
3         20809  2022-06-04  08:41:23          LEVI RIBEIRO AMORIM
4         47123  2019-05-04  13:38:45  GABRIEL MATOS LIMA DA CUNHA

            produto  valor  quantidade   total                status  \
0  Queijo Mussarela  16.87          13  239.31  Pagamento Confirmado
1   Molho de Tomate   3.25           3    9.75  Pagamento Confirmado
2      Água Mineral   1.63           9   36.67  Pagamento Confirmado
3            Carvão   8.74           4   54.96          Em Separação
4              Café   9.48           2   18.96          Em Separação

                  cidade estado    pais        cep  frete  \
0                Niterói     RJ  Brasil  24000-000   20.0
1                Mariana     MG  Brasil  35420-000   12.0
2              Cabo Frio     RJ  Brasil  28900-000   22.0
3  Campos dos Goytacazes     RJ  Brasil  28000-000   20.0
4   Conselheiro Lafaiete     MG  Brasil  36400-000   10.5

                pagamento                            vendedor         marca  \
0       Cartão de Crédito             SAMUEL HENRIQUE CAÇADOR  Porto Alegre
1                     Pix  MICAEL MALAQUIAS DE SOUZA OLIVEIRA        Fugini
2  Transferência Bancária         HENRICO MATOS LIMA DA CUNHA       Minalba
3                     Pix           GABRIEL QUEIROZ DE AGUIAR    Marca-Brás
4       Cartão de Crédito         HENRICO MATOS LIMA DA CUNHA    3 Corações

  valor_formatado
0           16.87
1            3.25
2            1.63
3            8.74
4            9.48

In [87]:
# Arredonda os valores da coluna 'valor' para 2 casas decimais, mantendo o tipo numérico
df['valor'] = df['valor'].apply(lambda x: round(x, 2))

# Verifica o resultado
print(df['valor'].head())

0    16.87
1     3.25
2     1.63
3     8.74
4     9.48
Name: valor, dtype: float64

In [88]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,16.87
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,3.25
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,1.63
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás,8.74
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações,9.48

In [89]:
# Exibe as 20 primeiras linhas
print(df.head(20))

    id_da_compra        data      hora  \
0          13679  2021-03-20  23:35:51
1          28070  2020-10-30  09:00:53
2          47484  2021-06-09  15:30:28
3          20809  2022-06-04  08:41:23
4          47123  2019-05-04  13:38:45
5          38623  2018-02-19  17:32:01
6          46627  2018-04-21  22:08:30
7          53579  2020-09-25  12:04:15
8          34924  2018-06-20  17:10:42
9          10575  2018-10-01  18:36:45
10         43813  2021-06-04  21:07:04
11          7597  2021-09-15  07:46:58
12         10784  2020-07-03  22:34:21
13          1271  2021-04-18  10:56:01
14         41008  2021-04-25  15:20:19
15          5650  2021-06-11  14:18:25
16         22499  2021-05-10  16:03:02
17         24847  2022-06-23  12:15:47
18         12051  2020-07-23  15:37:50
19         51716  2021-03-13  09:10:41

                                   cliente           produto  valor  \
0                        LUCAS Araujo Kuhn  Queijo Mussarela  16.87
1                     MICAEL SOUZA RONCETE   Molho de Tomate   3.25
2                FELIPE AUGUSTO NERY SILVA      Água Mineral   1.63
3                      LEVI RIBEIRO AMORIM            Carvão   8.74
4              GABRIEL MATOS LIMA DA CUNHA              Café   9.48
5              LUCAS ANTÔNIO DE SOUZA NETO              Café  10.16
6           GUILHERME IVAIR DE ASSIS SETTA            Feijão   7.77
7                   GABRIEL MUZY FERNANDES  Queijo Mussarela  14.93
8                 LEVI MATOS LIMA DA CUNHA     Condicionador   9.51
9                HENRICO DA CUNHA TEIXEIRA          Sabonete   1.25
10               PEDRO MATOS LIMA DA CUNHA            Açúcar   3.59
11        MATEUS LACERDA PORTUGAL DA SILVA      Água Mineral   1.63
12                     MATEUS VICTOR ALVES          Manteiga   6.61
13             CARLOS ASSIS NOGUEIRA SILVA   Papel Higiênico   3.89
14                  VICTOR SANTOS DA SILVA      Óleo de Soja   3.22
15                VICTOR DA CUNHA TEIXEIRA              Café   5.29
16  HENRIQUE PICANÇO SANTOS FERREIRA SILVA              Café   9.35
17        THIAGO LACERDA PORTUGAL DA SILVA            Açúcar   3.75
18                  ARTHUR FELIPE DE SOUZA              Café   9.45
19                   MIGUEL MURATORI DUTRA   Molho de Tomate   3.31

    quantidade   total                status                 cidade estado  \
0           13  239.31  Pagamento Confirmado                Niterói     RJ
1            3    9.75  Pagamento Confirmado                Mariana     MG
2            9   36.67  Pagamento Confirmado              Cabo Frio     RJ
3            4   54.96          Em Separação  Campos dos Goytacazes     RJ
4            2   18.96          Em Separação   Conselheiro Lafaiete     MG
5            1   20.16  Entregue com Sucesso          Resende Costa     MG
6            3   43.31          Em Separação              São Paulo     SP
7           14  218.02          Em Separação                  Bicas     MG
8            5   69.55  Pagamento Confirmado              Cabo Frio     RJ
9            2   13.00          Em Separação       São João del-Rei     MG
10           1    3.59  Aguardando Pagamento            São Gonçalo     RJ
11          13   39.19  Aguardando Pagamento  São Bernardo do Campo     SP
12           8   71.88         Em Transporte        Duque de Caxias     RJ
13          12   46.68          Em Separação                  Macaé     RJ
14          12   58.64  Pagamento Confirmado              São Paulo     SP
15           1    5.29          Em Separação                 Viçosa     MG
16           2   18.70          Em Separação          Resende Costa     MG
17           3   24.25          Em Separação           Juiz de Fora     MG
18           3   28.35                    AP              Guarulhos     SP
19           2    6.62          Em Separação         Matias Barbosa     MG

      pais        cep  frete               pagamento  \
0   Brasil  24000-000   20.0       Cartão de Crédito
1   Brasil  35420-000   12.0                     Pix
2   Brasil  28900-000   22.0  Transferência Bancária
3   Brasil  28000-000   20.0                     Pix
4   Brasil  36400-000   10.5       Cartão de Crédito
5   Brasil  36340-000   10.0  Transferência Bancária
6   Brasil  01000-000   20.0                     Pix
7   Brasil  36600-000    9.0                  Boleto
8   Brasil  28900-000   22.0                     Pix
9   Brasil  36300-000   10.5                  Boleto
10  Brasil  24400-000   20.0  Transferência Bancária
11  Brasil  09700-000   18.0       Cartão de Crédito
12  Brasil  25000-000   19.0             Pix à Vista
13  Brasil  27900-000   20.0  Transferência Bancária
14  Brasil  01000-000   20.0       Cartão de Crédito
15  Brasil  36570-000    9.0  Transferência Bancária
16  Brasil  36340-000   10.0                     Pix
17  Brasil  36000-000   13.0  Transferência Bancária
18  Brasil  07000-000   18.0                  Boleto
19  Brasil  36120-000   10.0       Cartão de Crédito

                                vendedor         marca valor_formatado
0                SAMUEL HENRIQUE CAÇADOR  Porto Alegre           16.87
1     MICAEL MALAQUIAS DE SOUZA OLIVEIRA        Fugini            3.25
2            HENRICO MATOS LIMA DA CUNHA       Minalba            1.63
3              GABRIEL QUEIROZ DE AGUIAR    Marca-Brás            8.74
4            HENRICO MATOS LIMA DA CUNHA    3 Corações            9.48
5              VICTOR GONÇALVES DONADONI    3 Corações           10.16
6                SAMUEL HENRIQUE CAÇADOR     Caldo Bom            7.77
7     MICAEL MALAQUIAS DE SOUZA OLIVEIRA  Porto Alegre           14.93
8   FELIPE HENRIQUE COSTA BARNABE MARAZO       Pantene            9.51
9              GABRIEL QUEIROZ DE AGUIAR          Dove            1.25
10               SAMUEL HENRIQUE CAÇADOR     Caravelas            3.59
11                  HENRICO VICTOR ALVES       Crystal            1.63
12               SAMUEL HENRIQUE CAÇADOR        Itambé            6.61
13    MICAEL MALAQUIAS DE SOUZA OLIVEIRA          Neve            3.89
14           HENRICO MATOS LIMA DA CUNHA          Liza            3.22
15    MICAEL MALAQUIAS DE SOUZA OLIVEIRA    3 Corações            5.29
16             GABRIEL QUEIROZ DE AGUIAR    3 Corações            9.35
17               SAMUEL HENRIQUE CAÇADOR     Caravelas            3.75
18                  HENRICO VICTOR ALVES    3 Corações            9.45
19              CARLOS QUEIROZ DE AGUIAR    Predilecta            3.31

In [90]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,16.87
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,3.25
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,1.63
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás,8.74
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações,9.48

In [91]:
df['frete'] = df['frete'].apply(lambda x: f"{x:.2f}")

In [92]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.00,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,16.87
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.00,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,3.25
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.00,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,1.63
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.00,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás,8.74
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.50,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações,9.48

In [93]:
#visualizar os produtos lux
# Filtra produtos que contenham 'lux' no nome (sem diferenciar maiúsculas/minúsculas)
produtos_lux = df[df['marca'].str.contains('lux', case=False, na=False)]

# Exibe apenas a coluna 'produto' e 'valor' desses itens
print(produtos_lux[['marca', 'valor']].head(10))  # Mostra os 10 primeiros

    marca   valor
88    Lux    1.94
117   Lux    2.23
167   Lux    1.29
170   Lux    2.46
281   Lux    2.56
354   Lux    1.31
451   Lux    1.39
469   Lux    2.68
495   Lux  168.99
575   Lux    1.31

In [94]:
#vamos achar a mediana para definir o valor correto do outlier
# Calcula o IQR (Intervalo Interquartil)
Q1 = produtos_lux['valor'].quantile(0.25)
Q3 = produtos_lux['valor'].quantile(0.75)
IQR = Q3 - Q1

# Define os limites sem outliers
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Filtra sem os outliers
lux_sem_outliers = produtos_lux[(produtos_lux['valor'] >= limite_inferior) & (produtos_lux['valor'] <= limite_superior)]

mediana_lux = lux_sem_outliers['valor'].median()
print(f"Mediana dos produtos 'lux' (sem outliers): {mediana_lux}")

Mediana dos produtos 'lux' (sem outliers): 2.0

In [95]:
#agora vamos substituir o outlier
# Identifica os índices dos outliers
outliers_idx = produtos_lux[(produtos_lux['valor'] < limite_inferior) | (produtos_lux['valor'] > limite_superior)].index

# Substitui os valores nos índices de outliers pela mediana
df.loc[outliers_idx, 'valor'] = mediana_lux

In [96]:
#vamos verificar a alteracao agora
# Filtra produtos que contenham 'lux' no nome (sem diferenciar maiúsculas/minúsculas)
produtos_lux = df[df['marca'].str.contains('lux', case=False, na=False)]

# Exibe apenas a coluna 'produto' e 'valor' desses itens
print(produtos_lux[['marca', 'valor']].head(10))  # Mostra os 10 primeiros

    marca  valor
88    Lux   1.94
117   Lux   2.23
167   Lux   1.29
170   Lux   2.46
281   Lux   2.56
354   Lux   1.31
451   Lux   1.39
469   Lux   2.68
495   Lux   2.00
575   Lux   1.31

In [97]:
#agora vamos verificar se esta tudo escrito correto nos pagamentos
pagamento_unicos = df['pagamento'].unique()
pagamento_unicos_list = pagamento_unicos.tolist()
for pagamento in pagamento_unicos_list:
    print(pagamento)

Cartão de Crédito
Pix
Transferência Bancária
Boleto
Pix à Vista
Cartão Crédito à Vista
Pagamento Instantâneo
Cartão Crédito
Boleto à Vista
DOC
TED
Boleto no Dinheiro

In [98]:
#vamos tratar essas escritas erradas


# Função para normalizar o texto
def normalizar(texto):
    return (str(texto)).strip().lower()

# Aplica a normalização para facilitar o mapeamento
df['pagamento_normalizado'] = df['pagamento'].apply(normalizar)

# Dicionário de mapeamento normalizado → padronizado
mapeamento_pagamento = {
    'cartao de credito': 'Cartão de Crédito',
    'pix': 'Pix',
    'transferencia bancaria': 'Transferência Bancária',
    'boleto': 'Boleto',
    'pix a vista': 'Pix',
    'cartao credito a vista': 'Cartão Crédito à Vista',
    'pagamento instantaneo': 'Pagamento Instantâneo',
    'boleto à vista': 'Boleto',
    'doc': 'DOC',
    'ted': 'TED',
    'boleto no dinheiro': 'Boleto',
    'cartão de crédito': 'Cartão de Crédito',
    'transferência bancária' : 'Transferência Bancária',
    'pix à vista' : 'Pix',
    'cartão crédito à vista' : 'Cartão Crédito à Vista',
    'pagamento instantâneo' : 'Pagamento Instantâneo',    
}

# Aplica o mapeamento para a coluna original
df['pagamento'] = df['pagamento_normalizado'].replace(mapeamento_pagamento)

# Remove a coluna auxiliar se quiser
df.drop(columns=['pagamento_normalizado'], inplace=True)

In [99]:
#agora vamos verificar se esta tudo escrito correto nos pagamentos
pagamento_unicos = df['pagamento'].unique()
pagamento_unicos_list = pagamento_unicos.tolist()
for pagamento in pagamento_unicos_list:
    print(pagamento)

Cartão de Crédito
Pix
Transferência Bancária
Boleto
Cartão Crédito à Vista
Pagamento Instantâneo
cartão crédito
DOC
TED

In [100]:
# Salva o DataFrame como CSV na pasta 'working'
df.to_csv('/kaggle/working/vendas_limpo.csv', index=False)

# Confirmação
print("Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv")

Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv

In [101]:
# Ver marcas únicas
marcas_unicas = df['marca'].unique()

# Exibir todas as marcas
for marca in marcas_unicas:
    print(marca)

Porto Alegre
Fugini
Minalba
Marca-Brás
3 Corações
Caldo Bom
Pantene
Dove
Caravelas
Crystal
Itambé
Neve
Liza
Predilecta
Pilão
Seda
Melitta
Salton
Adria
Coamo
Aurora
Skol
União
Scott
Miolo
Oral-B
Aviação
Itamarati
Nutrella
Sorriso
Brilhante
Elefante
Snob
Confort
Pinho Sol
Coca-Cola
Nivea
Lysoform
Tirolez
Kicaldo
Colgate
Concha y Toro
Urbano
Sol
Fofo
Triunfo
Quatá
Lebre
Prats
Dona Benta
Bauducco
Lux
Ypê
Dafruta
Barilla
Elite
Tixan
Elegê
Tio João
Minuano
Soya
Renata
Dualette
Wickbold
Nestlé
Qualy
Cisne
Pullman
Marinho
Fanta
Limpol
Perdigão
Guaraná Antártica
Veja
Brahma
Omo
Heineken
Genérico
Del Valle
Anaconda
Personal
Sadia
Namorado
São Lourenço
Ki-Brasa
Downy
Camil
Piracanjuba

In [102]:
#vamos ver os outliers de valor:

outliers_por_marca = []

# Percorre cada marca separadamente
for marca, grupo in df.groupby('marca'):
    q1 = grupo['valor'].quantile(0.25)
    q3 = grupo['valor'].quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr

    # Filtra os outliers
    outliers = grupo[(grupo['valor'] < limite_inferior) | (grupo['valor'] > limite_superior)]
    outliers_por_marca.append(outliers)

# Junta todos os outliers encontrados
df_outliers = pd.concat(outliers_por_marca)

# Visualiza os outliers encontrados
df_outliers[['marca', 'valor']]

             marca    valor
5779    3 Corações  1679.42
6127    3 Corações   774.21
7297    3 Corações  1206.51
7543    3 Corações  1129.22
8789    3 Corações  1623.09
...            ...      ...
361269         Ypê   487.32
361461         Ypê     1.52
362825         Ypê   413.96
366107         Ypê     4.61
368663         Ypê   480.77

[9886 rows x 2 columns]

In [103]:
#agora vamos tratar:

mediana_valor_por_marca = df[df['valor'] > 0].groupby('marca')['valor'].median()

import numpy as np

# Função para identificar e corrigir outliers de 'valor' por marca
def tratar_outliers(grupo):
    q1 = grupo['valor'].quantile(0.25)
    q3 = grupo['valor'].quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr

    mediana = grupo['valor'].median()

    # Substitui valores fora dos limites pela mediana
    grupo['valor'] = grupo['valor'].apply(lambda x: mediana if (x < limite_inferior or x > limite_superior) else x)
    return grupo

df = df.groupby('marca', group_keys=False).apply(tratar_outliers)

<ipython-input-103-327b8cfce1a7>:21: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('marca', group_keys=False).apply(tratar_outliers)

In [104]:
print(df[['marca', 'valor']].head(10))  # ver como ficaram os primeiros valores tratados

          marca  valor
0  Porto Alegre  16.87
1        Fugini   3.25
2       Minalba   1.63
3    Marca-Brás   8.74
4    3 Corações   9.48
5    3 Corações  10.16
6     Caldo Bom   7.77
7  Porto Alegre  14.93
8       Pantene   9.51
9          Dove   1.25

In [105]:
#verificar novamente se existe:

outliers_por_marca = []

# Percorre cada marca separadamente
for marca, grupo in df.groupby('marca'):
    q1 = grupo['valor'].quantile(0.25)
    q3 = grupo['valor'].quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr

    # Filtra os outliers
    outliers = grupo[(grupo['valor'] < limite_inferior) | (grupo['valor'] > limite_superior)]
    outliers_por_marca.append(outliers)

# Junta todos os outliers encontrados
df_outliers = pd.concat(outliers_por_marca)

# Visualiza os outliers encontrados
df_outliers[['marca', 'valor']]

             marca  valor
3356    3 Corações   4.79
6733    3 Corações   4.52
22822   3 Corações  15.34
30468   3 Corações  15.34
35980   3 Corações  15.36
...            ...    ...
233514         Ypê   1.64
238901         Ypê   1.65
270245         Ypê   1.62
285385         Ypê   4.40
298870         Ypê   1.67

[1825 rows x 2 columns]

In [106]:
# Vamos converter denovo para tipo numericos
colunas_numericas = ['valor', 'quantidade', 'frete', 'total']
for col in colunas_numericas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [107]:
#verificando:
print(df[colunas_numericas].dtypes)

valor         float64
quantidade      int64
frete         float64
total         float64
dtype: object

In [108]:
#recalcular o valor total de forma correta agora
df['total'] = (df['valor'] * df['quantidade']) + df['frete']

In [109]:
# Salva o DataFrame como CSV na pasta 'working'
df.to_csv('/kaggle/working/vendas_limpo2.csv', index=False)

# Confirmação
print("Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv")

Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv

In [110]:
#vamos converter a data para datetime:
df['data'] = pd.to_datetime(df['data'])

In [111]:
#vamos padronizar agora as informações que não foram padronizadas anteriormente:

df['cliente'] = df['cliente'].str.strip().str.title()
df['produto'] = df['produto'].str.strip().str.title()
df['status'] = df['status'].str.strip().str.title()
df['cidade'] = df['cidade'].str.strip().str.title()
df['estado'] = df['estado'].str.strip().str.upper()
df['pais'] = df['pais'].str.strip().str.title()
df['pagamento'] = df['pagamento'].str.strip().str.title()
df['vendedor'] = df['vendedor'].str.strip().str.title()
df['marca'] = df['marca'].str.strip().str.title()

In [112]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,21.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,54.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,29.46,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48

In [113]:
#o frete voltou com uma casa decimal:

# Garante que a coluna está em float
df['frete'] = pd.to_numeric(df['frete'], errors='coerce')

# Formata com 2 casas decimais (exibição)
df['frete'] = df['frete'].round(2)

# Apenas para exibir com 2 casas decimais fixas (como string formatada)
df['frete_formatado'] = df['frete'].map('{:.2f}'.format)

In [114]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,21.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,54.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,29.46,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50

In [115]:
print(df['frete_formatado'].dtype)

object

In [116]:
#se apareceu como object eh porque tem valores mal formatado
#vou tratar agora:

# Remove espaços em branco e troca vírgulas por ponto decimal (se houver)
df['frete'] = df['frete'].astype(str).str.strip().str.replace(',', '.')

# Converte para float (valores inválidos viram NaN)
df['frete'] = pd.to_numeric(df['frete'], errors='coerce')

# Arredonda para duas casas decimais
df['frete'] = df['frete'].round(2)

In [117]:
print(df['frete'].dtype)

float64

In [118]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,21.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,54.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,29.46,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50

In [119]:
#o frete voltou com uma casa decimal:

# Garante que a coluna está em float
df['frete'] = pd.to_numeric(df['frete'], errors='coerce')

# Formata com 2 casas decimais (exibição)
df['frete'] = df['frete'].round(2)

# Apenas para exibir com 2 casas decimais fixas (como string formatada)
df['frete_formatado'] = df['frete'].map('{:.2f}'.format)

In [120]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,21.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,54.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,29.46,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50

In [121]:
df['frete'] = df['frete'].round(2)

In [122]:
print(df['frete_formatado'].dtype)  # Deve retornar float64
print(df['frete_formatado'].head())  # Mostra os primeiros valores com duas casas decimais

object
0    20.00
1    12.00
2    22.00
3    20.00
4    10.50
Name: frete_formatado, dtype: object

In [123]:
print("Valores nulos em 'frete':", df['frete'].isna().sum())

print("Valores negativos em 'frete':", (df['frete'] < 0).sum())

print("Tipo da coluna 'frete':", df['frete'].dtype)

print(df['frete'].sample(10))  # Mostra 10 exemplos aleatórios

Valores nulos em 'frete': 0
Valores negativos em 'frete': 0
Tipo da coluna 'frete': float64
345036     9.5
192709     9.0
40634     17.0
11760     18.0
178376    11.0
195824     8.5
82073     20.0
297039    18.0
122344    23.0
215711    19.0
Name: frete, dtype: float64

In [124]:
print(df['valor'].dtype) 

print(df['frete'].dtype)

print(df['total'].dtype) 

print(df['valor_formatado'].dtype)

float64
float64
float64
object

In [125]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,21.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,54.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,29.46,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50

In [126]:
#verificar as diferencas das colunas
diferentes = df[df['valor'] != df['valor_formatado']]
print(diferentes[['valor', 'valor_formatado']].head())

   valor valor_formatado
0  16.87           16.87
1   3.25            3.25
2   1.63            1.63
3   8.74            8.74
4   9.48            9.48

In [127]:
#criar duas colunas, onde uma sera com frete e outra sem
df['total_com_frete'] = df['total']

In [128]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado,total_com_frete
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00,239.31
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,21.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00,21.75
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00,36.67
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,54.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00,54.96
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,29.46,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50,29.46

In [129]:
df['total'] = df['total'] - df['frete']

In [130]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado,total_com_frete
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00,239.31
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00,21.75
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00,36.67
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00,54.96
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50,29.46

In [131]:
#pronto agora temos uma coluna de total sem frete e outra com frete
df.rename(columns={'total': 'total_sem_frete'}, inplace=True)

In [132]:
df.head(

)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,frete_formatado,total_com_frete
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,20.00,239.31
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,12.00,21.75
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,22.00,36.67
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,20.00,54.96
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,10.50,29.46

In [133]:
df.drop(columns=['frete_formatado'], inplace=True)

In [134]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,valor_formatado,total_com_frete
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,16.87,239.31
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,3.25,21.75
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,1.63,36.67
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,8.74,54.96
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,9.48,29.46

In [135]:
df.drop(columns=['valor_formatado'], inplace=True)

In [136]:
# Salva o DataFrame como CSV na pasta 'working'
df.to_csv('/kaggle/working/vendas_limpo3.csv', index=False)

# Confirmação
print("Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv")

Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv

In [137]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,total_com_frete
0,13679,2021-03-20,23:35:51,Lucas Araujo Kuhn,Queijo Mussarela,16.87,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,239.31
1,28070,2020-10-30,09:00:53,Micael Souza Roncete,Molho De Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,21.75
2,47484,2021-06-09,15:30:28,Felipe Augusto Nery Silva,Água Mineral,1.63,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,36.67
3,20809,2022-06-04,08:41:23,Levi Ribeiro Amorim,Carvão,8.74,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,54.96
4,47123,2019-05-04,13:38:45,Gabriel Matos Lima Da Cunha,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,29.46

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365072 entries, 0 to 368751
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_da_compra     365072 non-null  int64
 1   data             365072 non-null  datetime64[ns]
 2   hora             365072 non-null  object
 3   cliente          365072 non-null  object
 4   produto          365072 non-null  object
 5   valor            365072 non-null  float64
 6   quantidade       365072 non-null  int64
 7   total_sem_frete  365072 non-null  float64
 8   status           365072 non-null  object
 9   cidade           365072 non-null  object
 10  estado           365072 non-null  object
 11  pais             365072 non-null  object
 12  cep              365072 non-null  object
 13  frete            365072 non-null  float64
 14  pagamento        365072 non-null  object
 15  vendedor         365072 non-null  object
 16  marca            365072 non-null  object
 17  total_com_frete  365072 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(11)
memory usage: 61.0+ MB

In [139]:
#vamos transformar as horas

df['hora'] = pd.to_datetime(df['hora'], format='%H:%M:%S', errors='coerce')

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365072 entries, 0 to 368751
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_da_compra     365072 non-null  int64
 1   data             365072 non-null  datetime64[ns]
 2   hora             365072 non-null  datetime64[ns]
 3   cliente          365072 non-null  object
 4   produto          365072 non-null  object
 5   valor            365072 non-null  float64
 6   quantidade       365072 non-null  int64
 7   total_sem_frete  365072 non-null  float64
 8   status           365072 non-null  object
 9   cidade           365072 non-null  object
 10  estado           365072 non-null  object
 11  pais             365072 non-null  object
 12  cep              365072 non-null  object
 13  frete            365072 non-null  float64
 14  pagamento        365072 non-null  object
 15  vendedor         365072 non-null  object
 16  marca            365072 non-null  object
 17  total_com_frete  365072 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(10)
memory usage: 61.0+ MB

In [141]:
df['hora'] = pd.to_datetime(df['hora'], format='%H:%M:%S', errors='coerce')

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365072 entries, 0 to 368751
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_da_compra     365072 non-null  int64
 1   data             365072 non-null  datetime64[ns]
 2   hora             365072 non-null  datetime64[ns]
 3   cliente          365072 non-null  object
 4   produto          365072 non-null  object
 5   valor            365072 non-null  float64
 6   quantidade       365072 non-null  int64
 7   total_sem_frete  365072 non-null  float64
 8   status           365072 non-null  object
 9   cidade           365072 non-null  object
 10  estado           365072 non-null  object
 11  pais             365072 non-null  object
 12  cep              365072 non-null  object
 13  frete            365072 non-null  float64
 14  pagamento        365072 non-null  object
 15  vendedor         365072 non-null  object
 16  marca            365072 non-null  object
 17  total_com_frete  365072 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(10)
memory usage: 61.0+ MB

In [143]:
# Para todas as colunas do tipo objeto (texto)
for col in df.select_dtypes(include='object').columns:
    print(f"\nValores únicos da coluna '{col}':")
    print(df[col].unique())

Valores únicos da coluna 'cliente':
['Lucas Araujo Kuhn' 'Micael Souza Roncete' 'Felipe Augusto Nery Silva'
 'Levi Ribeiro Amorim' 'Gabriel Matos Lima Da Cunha'
 'Lucas Antônio De Souza Neto' 'Guilherme Ivair De Assis Setta'
 'Gabriel Muzy Fernandes' 'Levi Matos Lima Da Cunha'
 'Henrico Da Cunha Teixeira' 'Pedro Matos Lima Da Cunha'
 'Mateus Lacerda Portugal Da Silva' 'Mateus Victor Alves'
 'Carlos Assis Nogueira Silva' 'Victor Santos Da Silva'
 'Victor Da Cunha Teixeira' 'Henrique Picanço Santos Ferreira Silva'
 'Thiago Lacerda Portugal Da Silva' 'Arthur Felipe De Souza'
 'Miguel Muratori Dutra' 'João Silvino Da Silva'
 'Henrique Henrique Caçador' 'Pedro Souza Roncete'
 'Matheus Silvino Da Silva' 'Samuel Augusto Nery Silva'
 'Pedro Vitor Façanha Neves' 'Guilherme Hugo Cazula Pereira'
 'João Queiroz De Aguiar' 'João Matos Lima Da Cunha'
 'Victor Muratori Dutra' 'Mateus Stanzani De Jesus'
 'Thiago Antônio De Decco Oliveira' 'Mateus Antônio De Decco Oliveira'
 'Henrico Matheus Da Silva' 'Felipe Da Silva Bianquini'
 'Matheus Gonçalves Donadoni' 'Guilherme Castilho Cardoso'
 'Felipe Matos Lima Da Cunha' 'Victor Silva Ramos'
 'Gabriel Felipe De Souza' 'Gabriel Castilho Cardoso'
 'Pedro Assis Nogueira Silva' 'Rafael Matheus Da Silva'
 'Mateus Vieira Demarque' 'Hian Cardoso Diniz'
 'Breno Wilstony De Souza Mendes' 'Gabriel Souza Roncete'
 'Paulo Queiroz De Aguiar' 'Levi Antônio De Souza Neto'
 'Arthur Augusto De Sousa Ferrari' 'Yuri Vieira Demarque'
 'Yuri Muzy Fernandes' 'Levi Silva Ramos' 'Thiago Ribeiro Amorim'
 'Matheus Antônio De Decco Oliveira' 'Mateus Cardoso Diniz'
 'Lucas Breno Prado Silva' 'Matheus Augusto Nery Silva'
 'Marco Ribeiro Amorim' 'Miguel Wilstony De Souza Mendes'
 'Henrico Silvino Da Silva' 'Felipe Da Cunha Teixeira'
 'Marco Lacerda Portugal Da Silva' 'Matheus Victor Alves'
 'Gabriel Muratori Dutra' 'Mateus Augusto Nery Silva' 'Pedro Victor Alves'
 'Lucas Carlos De Souza' 'Samuel Vitor Façanha Neves'
 'Leticia Castilho Cardoso' 'Marco Hugo Cazula Pereira'
 'Henrico Ribeiro Amorim' 'Victor Antônio De Souza Neto'
 'Victor Muzy Fernandes' 'Gabriel Henrique Caçador'
 'Matheus Werneck Elizeu' 'Mateus Matos Lima Da Cunha'
 'Hian Hugo Cazula Pereira' 'Lucas Lacerda Portugal Da Silva'
 'Yuri Ribas De Moura' 'João Assis Nogueira Silva'
 'Victor Henrique Costa Barnabe Marazo' 'Marco Cunha De Oliveira'
 'Micael Victor Alves' 'João Da Silva Bianquini' 'Lucas Victor Alves'
 'Breno Breno Prado Silva' 'Yuri Assis Nogueira Silva'
 'Yuri Augusto Nery Silva' 'Marco Santos Da Silva'
 'Thiago Vieira Demarque' 'Tiago Gonçalves Dos Santos'
 'Gabriel Assis Nogueira Silva' 'Carlos Antônio De Decco Oliveira'
 'Matheus Gonçalves Dos Santos' 'Breno Malaquias De Souza Oliveira'
 'Kallebe Victor Alves' 'Lucas Gonçalves Donadoni'
 'Yuri Malaquias De Souza Oliveira' 'Hian Stanzani De Jesus'
 'Henrique Antônio De Decco Oliveira' 'Paulo Castilho Cardoso'
 'Leticia Vieira Demarque' 'Samuel Hugo Cazula Pereira'
 'Paulo Hugo Cazula Pereira' 'Thiago Ribas De Moura'
 'Lucas Henrique Caçador' 'Mateus Vitor Façanha Neves'
 'Henrico Malaquias De Souza Oliveira' 'Marco Vitor Façanha Neves'
 'Paulo Da Silva Bianquini' 'Rafael Carlos De Souza'
 'João Henrique Costa Barnabe Marazo' 'Guilherme Paulo Alves Alvim'
 'Kallebe Antônio De Souza Neto' 'Lucas Santos Da Silva'
 'Victor Henrique Caçador' 'Tiago José Silva Matias'
 'Gabriel Paulo Alves Alvim' 'Mateus Queiroz De Aguiar'
 'Hian Cunha De Oliveira' 'Kallebe Ribas De Moura' 'Victor Souza Roncete'
 'Samuel Muzy Fernandes' 'João Hugo Cazula Pereira' 'João Souza Roncete'
 'Rafael Hugo Cazula Pereira' 'Carlos Picanço Santos Ferreira Silva'
 'Rafael Vitor Façanha Neves' 'Rafael Antônio De Souza Neto'
 'Blendow Henrique Costa Barnabe Marazo' 'Samuel Vieira Demarque'
 'Matheus Silva Ramos' 'Mateus Paulo Alves Alvim' 'Levi Souza Roncete'
 'Samuel Gonçalves Donadoni' 'Henrique Santos Da Silva'
 'Felipe Carlos De Souza' 'João Ribas De Moura' 'Henrique Werneck Elizeu'
 'Rafael Felipe De Souza' 'João Silva Ramos' 'Rafael Muzy Fernandes'
 'Rafael Da Silva Bianquini' 'Rafael Augusto Nery Silva'
 'Yuri Risson Euzebio' 'Samuel Antônio De Decco Oliveira'
 'Victor Castilho Cardoso' 'Victor Lacerda Portugal Da Silva'
 'Carlos Matheus Da Silva' 'Felipe Silvino Da Silva'
 'Gabriel Gonçalves Dos Santos' 'Rafael Risson Euzebio'
 'Yuri Souza Roncete' 'João Muzy Fernandes' 'Mateus Gonçalves Dos Santos'
 'Arthur Malaquias De Souza Oliveira' 'Felipe Muzy Fernandes'
 'Victor Matheus Da Silva' 'Rômulo Henrique Costa Barnabe Marazo'
 'Victor Picanço Santos Ferreira Silva' 'Breno Hugo Cazula Pereira'
 'Hian Ribeiro Amorim' 'Mateus Da Cunha Teixeira'
 'Gabriel Matheus Da Silva' 'Samuel Ivair De Assis Setta'
 'Micael Muratori Dutra' 'Breno Gonçalves Donadoni'
 'Paulo Augusto De Sousa Ferrari' 'Tiago Augusto De Sousa Ferrari'
 'Leticia Felipe De Souza' 'Gabriel Silva Ramos' 'Lucas Ribas De Moura'
 'Kallebe Werneck Elizeu' 'João Da Cunha Teixeira'
 'Miguel Augusto De Sousa Ferrari' 'Rafael Da Cunha Teixeira'
 'Gabriel Da Cunha Teixeira' 'Levi Muzy Fernandes' 'Samuel Cardoso Diniz'
 'Pedro Gonçalves Dos Santos' 'Henrique Cunha De Oliveira'
 'Tiago Matheus Da Silva' 'Samuel Ribeiro Amorim' 'Carlos Ribeiro Amorim'
 'Guilherme Da Cunha Teixeira' 'Blendow José Silva Matias'
 'Gabriel Augusto De Sousa Ferrari' 'João Felipe De Souza'
 'Gabriel Picanço Santos Ferreira Silva' 'Mateus Augusto De Sousa Ferrari'
 'Micael Segurasse Gonçalves' 'Pedro Stanzani De Jesus'
 'Leticia Matos Lima Da Cunha' 'Kallebe Vitor Façanha Neves'
 'Samuel Silva Ramos' 'Matheus Lacerda Portugal Da Silva'
 'Rômulo Cunha De Oliveira' 'Leticia Augusto De Sousa Ferrari'
 'Matheus Vieira Demarque' 'Hian Segurasse Gonçalves'
 'Gabriel Ribeiro Amorim' 'Mateus Matheus Da Silva'
 'Pedro Felipe De Souza' 'Miguel Silva Ramos' 'Matheus Risson Euzebio'
 'Gabriel Gonçalves Donadoni' 'Levi Stanzani De Jesus'
 'Matheus Assis Nogueira Silva' 'Henrico Lacerda Portugal Da Silva'
 'Blendow Paulo Alves Alvim' 'João Santos Da Silva'
 'Yuri Matos Lima Da Cunha' 'João Antônio De Decco Oliveira'
 'Pedro Augusto De Sousa Ferrari' 'João Henrique Caçador'
 'Levi Felipe De Souza' 'Marco Da Silva Bianquini'
 'Samuel Lacerda Portugal Da Silva' 'Gabriel Lacerda Portugal Da Silva'
 'Carlos Felipe De Souza' 'Breno Cardoso Diniz' 'Rômulo Silva Ramos'
 'Miguel Augusto Nery Silva' 'Thiago Matos Lima Da Cunha'
 'Paulo Antônio De Souza Neto' 'Matheus Carlos De Souza'
 'Gabriel Carlos De Souza' 'Lucas Gonçalves Dos Santos'
 'Felipe Queiroz De Aguiar' 'Pedro Carlos De Souza'
 'Yuri Picanço Santos Ferreira Silva' 'João Stanzani De Jesus'
 'Blendow Silva Ramos' 'Yuri Gonçalves Donadoni' 'Pedro Ribas De Moura'
 'Pedro Santos Da Silva' 'Victor Silvino Da Silva'
 'Pedro Gonçalves Donadoni' 'Levi Ribas De Moura'
 'Samuel Queiroz De Aguiar' 'Samuel Matos Lima Da Cunha'
 'Marco Augusto De Sousa Ferrari' 'Pedro Muzy Fernandes'
 'Victor Malaquias De Souza Oliveira' 'Carlos Gonçalves Dos Santos'
 'Levi Araujo Kuhn' 'Yuri Muratori Dutra'
 'Lucas Antônio De Decco Oliveira' 'João Risson Euzebio'
 'Gabriel Augusto Nery Silva' 'Tiago Da Silva Bianquini'
 'Victor Wilstony De Souza Mendes' 'Henrico Carlos De Souza'
 'João Vieira Demarque' 'Carlos Ivair De Assis Setta'
 'Gabriel Segurasse Gonçalves' 'Yuri José Silva Matias'
 'Tiago Matos Lima Da Cunha' 'Victor Felipe De Souza'
 'Pedro Vieira Demarque' 'João Lacerda Portugal Da Silva'
 'Blendow Henrique Caçador' 'Rafael Castilho Cardoso'
 'Lucas Augusto Nery Silva' 'Breno Silvino Da Silva'
 'Mateus Felipe De Souza' 'Lucas Ivair De Assis Setta'
 'Victor José Silva Matias' 'Samuel Gonçalves Dos Santos'
 'João José Silva Matias' 'Breno Stanzani De Jesus'
 'Matheus Ivair De Assis Setta' 'Blendow Vieira Demarque'
 'Pedro Lacerda Portugal Da Silva' 'João Matheus Da Silva'
 'Thiago Queiroz De Aguiar' 'Marco Gonçalves Donadoni'
 'Levi Vitor Façanha Neves' 'Miguel Antônio De Decco Oliveira'
 'Matheus Ribeiro Amorim' 'Arthur Muratori Dutra'
 'Gabriel Breno Prado Silva' 'Samuel Carlos De Souza'
 'Marco Henrique Costa Barnabe Marazo' 'Mateus Werneck Elizeu'
 'Thiago Picanço Santos Ferreira Silva' 'Rafael Gonçalves Dos Santos'
 'Samuel Paulo Alves Alvim' 'Kallebe Augusto De Sousa Ferrari'
 'Samuel Malaquias De Souza Oliveira' 'Matheus Segurasse Gonçalves'
 'Gabriel José Silva Matias' 'Thiago Breno Prado Silva'
 'Rafael Henrique Costa Barnabe Marazo' 'João Araujo Kuhn'
 'Mateus Ribeiro Amorim' 'Thiago Henrique Caçador' 'Matheus Araujo Kuhn'
 'Mateus Hugo Cazula Pereira' 'Pedro Muratori Dutra'
 'Samuel Assis Nogueira Silva' 'Victor Araujo Kuhn'
 'Pedro Da Cunha Teixeira' 'Thiago Castilho Cardoso'
 'Leticia Matheus Da Silva' 'Samuel Castilho Cardoso'
 'Felipe Matheus Da Silva' 'Tiago Antônio De Decco Oliveira'
 'Victor Assis Nogueira Silva' 'Micael Gonçalves Dos Santos'
 'Rômulo Paulo Alves Alvim' 'Blendow Assis Nogueira Silva'
 'Hian Assis Nogueira Silva' 'Tiago Picanço Santos Ferreira Silva'
 'Breno Da Cunha Teixeira' 'Henrico Victor Alves'
 'Victor Ivair De Assis Setta' 'Micael Lacerda Portugal Da Silva'
 'Lucas Silvino Da Silva' 'Thiago Felipe De Souza'
 'João Vitor Façanha Neves' 'João Gonçalves Dos Santos'
 'João Antônio De Souza Neto' 'Yuri Victor Alves'
 'Henrico Paulo Alves Alvim' 'Arthur Cunha De Oliveira'
 'Hian Augusto De Sousa Ferrari' 'Pedro Wilstony De Souza Mendes'
 'Leticia Da Silva Bianquini' 'Victor Ribas De Moura'
 'Matheus Antônio De Souza Neto' 'Blendow Muratori Dutra'
 'Gabriel Antônio De Souza Neto' 'Guilherme Silvino Da Silva'
 'Matheus Malaquias De Souza Oliveira' 'Breno Antônio De Decco Oliveira'
 'Miguel Malaquias De Souza Oliveira' 'Thiago Stanzani De Jesus'
 'Miguel Victor Alves' 'Samuel Cunha De Oliveira'
 'Gabriel Stanzani De Jesus' 'Victor Ribeiro Amorim'
 'Yuri Cunha De Oliveira' 'Lucas Malaquias De Souza Oliveira'
 'Gabriel Henrique Costa Barnabe Marazo' 'Samuel Werneck Elizeu'
 'Guilherme Malaquias De Souza Oliveira' 'Lucas Risson Euzebio'
 'Thiago Cardoso Diniz' 'Victor Cunha De Oliveira'
 'Kallebe Ribeiro Amorim' 'Henrico Felipe De Souza'
 'Arthur Wilstony De Souza Mendes' 'Paulo Segurasse Gonçalves'
 'Miguel Vieira Demarque' 'Kallebe Araujo Kuhn'
 'Carlos Augusto De Sousa Ferrari' 'Gabriel Wilstony De Souza Mendes'
 'Leticia Souza Roncete' 'Lucas Ribeiro Amorim'
 'Henrique Augusto De Sousa Ferrari' 'Kallebe Matos Lima Da Cunha'
 'Samuel Augusto De Sousa Ferrari' 'Pedro Werneck Elizeu'
 'Gabriel Hugo Cazula Pereira' 'Gabriel Victor Alves'
 'Gabriel Cardoso Diniz' 'Kallebe Malaquias De Souza Oliveira'
 'Pedro Araujo Kuhn' 'Miguel Castilho Cardoso' 'Gabriel Werneck Elizeu'
 'Miguel Paulo Alves Alvim' 'Arthur Lacerda Portugal Da Silva'
 'Marco Felipe De Souza' 'Blendow Araujo Kuhn' 'Thiago José Silva Matias'
 'Rômulo Ribas De Moura' 'Kallebe Silva Ramos' 'Matheus Breno Prado Silva'
 'Victor Werneck Elizeu' 'Gabriel Vieira Demarque'
 'Arthur Ivair De Assis Setta' 'Samuel Da Cunha Teixeira'
 'Thiago Da Silva Bianquini' 'Hian Da Cunha Teixeira'
 'Paulo Muratori Dutra' 'Guilherme Ribas De Moura'
 'Henrique Augusto Nery Silva' 'Guilherme Victor Alves'
 'Pedro Malaquias De Souza Oliveira'
 'Blendow Picanço Santos Ferreira Silva' 'Kallebe Souza Roncete'
 'Rômulo Augusto Nery Silva' 'Paulo Santos Da Silva'
 'Thiago Segurasse Gonçalves' 'Matheus Muratori Dutra'
 'Victor Vitor Façanha Neves' 'João Breno Prado Silva'
 'Carlos Antônio De Souza Neto' 'Samuel Breno Prado Silva'
 'Gabriel Santos Da Silva' 'Marco Henrique Caçador'
 'Felipe Henrique Costa Barnabe Marazo' 'Levi Da Cunha Teixeira'
 'Arthur Souza Roncete' 'Micael Vieira Demarque'
 'Thiago Henrique Costa Barnabe Marazo'
 'Leticia Henrique Costa Barnabe Marazo' 'Lucas Paulo Alves Alvim'
 'Paulo Araujo Kuhn' 'Kallebe Wilstony De Souza Mendes'
 'Breno Santos Da Silva' 'Felipe Cardoso Diniz' 'Samuel Victor Alves'
 'Mateus José Silva Matias' 'Levi Paulo Alves Alvim'
 'Miguel Muzy Fernandes' 'Guilherme Gonçalves Donadoni'
 'Samuel Henrique Costa Barnabe Marazo' 'Henrique Gonçalves Donadoni'
 'Samuel Wilstony De Souza Mendes' 'Lucas Cunha De Oliveira'
 'Blendow Augusto Nery Silva' 'Arthur Da Cunha Teixeira'
 'Samuel José Silva Matias' 'Victor Hugo Cazula Pereira'
 'Mateus Ivair De Assis Setta' 'Matheus Vitor Façanha Neves'
 'Tiago Breno Prado Silva' 'Thiago Malaquias De Souza Oliveira'
 'Henrico Ivair De Assis Setta' 'Lucas Felipe De Souza'
 'Micael Da Silva Bianquini' 'Henrico Ribas De Moura'
 'João Augusto De Sousa Ferrari' 'Tiago Stanzani De Jesus'
 'Levi Malaquias De Souza Oliveira' 'Samuel Matheus Da Silva'
 'Carlos Castilho Cardoso' 'Rafael Araujo Kuhn' 'Mateus Muratori Dutra'
 'Felipe Cunha De Oliveira' 'Rômulo Assis Nogueira Silva'
 'Samuel Santos Da Silva' 'Gabriel Risson Euzebio' 'Paulo Victor Alves'
 'Gabriel Vitor Façanha Neves' 'Guilherme Antônio De Souza Neto'
 'Gabriel Antônio De Decco Oliveira' 'Pedro Silva Ramos'
 'Yuri Wilstony De Souza Mendes' 'Marco Da Cunha Teixeira'
 'Rafael Breno Prado Silva' 'Henrico Assis Nogueira Silva'
 'Hian Malaquias De Souza Oliveira' 'João Carlos De Souza'
 'Lucas Augusto De Sousa Ferrari' 'Arthur Antônio De Souza Neto'
 'Samuel Souza Roncete' 'Leticia Augusto Nery Silva'
 'Samuel Segurasse Gonçalves' 'Micael Malaquias De Souza Oliveira'
 'Breno Da Silva Bianquini' 'Pedro Da Silva Bianquini'
 'Arthur Breno Prado Silva' 'Samuel Muratori Dutra'
 'Blendow Gonçalves Dos Santos' 'Yuri Henrique Costa Barnabe Marazo'
 'Yuri Antônio De Decco Oliveira' 'Breno Segurasse Gonçalves'
 'Tiago Werneck Elizeu' 'Mateus Muzy Fernandes'
 'Felipe Malaquias De Souza Oliveira' 'Breno Felipe De Souza'
 'Felipe Vieira Demarque' 'Mateus Henrique Caçador'
 'Breno Ivair De Assis Setta' 'Rômulo Da Silva Bianquini'
 'Marco José Silva Matias' 'João Paulo Alves Alvim'
 'Yuri Henrique Caçador' 'Rômulo Henrique Caçador' 'Matheus Souza Roncete'
 'Victor Gonçalves Donadoni' 'Micael Henrique Costa Barnabe Marazo'
 'Guilherme Gonçalves Dos Santos' 'Lucas José Silva Matias'
 'Guilherme Henrique Costa Barnabe Marazo' 'Mateus Santos Da Silva'
 'Matheus Matos Lima Da Cunha' 'Blendow Carlos De Souza'
 'Gabriel Ribas De Moura' 'Matheus Castilho Cardoso' 'Levi Cardoso Diniz'
 'Arthur José Silva Matias' 'Felipe Werneck Elizeu'
 'Arthur Matheus Da Silva' 'João Picanço Santos Ferreira Silva'
 'Marco Antônio De Decco Oliveira' 'Paulo Souza Roncete'
 'Tiago Victor Alves' 'Victor Stanzani De Jesus' 'Henrico Araujo Kuhn'
 'Miguel Picanço Santos Ferreira Silva' 'Rômulo Cardoso Diniz'
 'Pedro Castilho Cardoso' 'Matheus Santos Da Silva'
 'Thiago Werneck Elizeu' 'Victor Augusto De Sousa Ferrari'
 'Mateus Araujo Kuhn' 'Guilherme Cunha De Oliveira'
 'Gabriel Ivair De Assis Setta' 'Rômulo Da Cunha Teixeira'
 'Marco Carlos De Souza' 'João Wilstony De Souza Mendes'
 'Miguel Ribas De Moura' 'Blendow Queiroz De Aguiar'
 'Levi Silvino Da Silva' 'Lucas Queiroz De Aguiar'
 'Henrique Stanzani De Jesus' 'Guilherme Assis Nogueira Silva'
 'Henrico Cardoso Diniz' 'Lucas Castilho Cardoso'
 'Blendow Gonçalves Donadoni' 'Kallebe Assis Nogueira Silva'
 'Carlos Matos Lima Da Cunha' 'Pedro Queiroz De Aguiar'
 'Guilherme Silva Ramos' 'Pedro Picanço Santos Ferreira Silva'
 'Rômulo Carlos De Souza' 'Micael Cardoso Diniz'
 'Henrique Matheus Da Silva' 'Thiago Gonçalves Dos Santos'
 'Hian Augusto Nery Silva' 'Pedro Antônio De Souza Neto'
 'Paulo Malaquias De Souza Oliveira' 'Rômulo Felipe De Souza'
 'Gabriel Silvino Da Silva' 'Gabriel Cunha De Oliveira'
 'Matheus Paulo Alves Alvim' 'Blendow Stanzani De Jesus'
 'Tiago Gonçalves Donadoni' 'Thiago Muzy Fernandes'
 'Felipe Felipe De Souza' 'Henrique Araujo Kuhn'
 'Henrique Assis Nogueira Silva' 'Carlos Cardoso Diniz'
 'Thiago Souza Roncete' 'Kallebe Gonçalves Dos Santos'
 'Rômulo Vieira Demarque' 'Lucas Da Cunha Teixeira'
 'Rômulo Lacerda Portugal Da Silva' 'Guilherme Henrique Caçador'
 'Carlos Souza Roncete' 'Gabriel Da Silva Bianquini'
 'Samuel Henrique Caçador' 'Matheus Augusto De Sousa Ferrari'
 'Hian Matos Lima Da Cunha' 'Kallebe Queiroz De Aguiar'
 'Matheus José Silva Matias' 'Matheus Henrique Costa Barnabe Marazo'
 'Rômulo Ivair De Assis Setta' 'Felipe Souza Roncete'
 'Henrique Wilstony De Souza Mendes' 'Victor Vieira Demarque'
 'Guilherme Santos Da Silva' 'Tiago Henrique Costa Barnabe Marazo'
 'Mateus Castilho Cardoso' 'Kallebe Hugo Cazula Pereira'
 'Matheus Hugo Cazula Pereira' 'Levi Henrique Costa Barnabe Marazo'
 'Leticia Carlos De Souza' 'Tiago Risson Euzebio' 'Levi Muratori Dutra'
 'Lucas Segurasse Gonçalves' 'Henrique Antônio De Souza Neto'
 'Pedro Ribeiro Amorim' 'Mateus Segurasse Gonçalves'
 'Kallebe Segurasse Gonçalves' 'Arthur Werneck Elizeu'
 'Hian Ivair De Assis Setta' 'Victor Matos Lima Da Cunha'
 'Yuri Hugo Cazula Pereira' 'Marco Malaquias De Souza Oliveira'
 'Henrique Ivair De Assis Setta' 'Henrico Da Silva Bianquini'
 'Samuel Da Silva Bianquini' 'Samuel Stanzani De Jesus'
 'Gabriel Malaquias De Souza Oliveira' 'Yuri Vitor Façanha Neves'
 'Victor Cardoso Diniz' 'Guilherme Cardoso Diniz'
 'Leticia Stanzani De Jesus' 'Victor Da Silva Bianquini'
 'Marco Matheus Da Silva' 'Yuri Queiroz De Aguiar'
 'Rafael Malaquias De Souza Oliveira' 'Levi Hugo Cazula Pereira'
 'Mateus Da Silva Bianquini' 'Hian Lacerda Portugal Da Silva'
 'Henrico Silva Ramos' 'Carlos Silva Ramos' 'Victor Gonçalves Dos Santos'
 'Rômulo José Silva Matias' 'Felipe Segurasse Gonçalves'
 'Pedro Ivair De Assis Setta' 'João Ivair De Assis Setta'
 'Carlos Werneck Elizeu' 'Mateus Wilstony De Souza Mendes'
 'Mateus Picanço Santos Ferreira Silva' 'Matheus Matheus Da Silva'
 'Breno Picanço Santos Ferreira Silva' 'Henrico Gonçalves Donadoni'
 'Marco Matos Lima Da Cunha' 'Thiago Antônio De Souza Neto'
 'Blendow Muzy Fernandes' 'Kallebe Antônio De Decco Oliveira'
 'Breno Werneck Elizeu' 'Kallebe Henrique Caçador'
 'Miguel Henrique Costa Barnabe Marazo' 'Paulo Matos Lima Da Cunha'
 'Yuri Castilho Cardoso' 'Hian Ribas De Moura' 'Carlos Queiroz De Aguiar'
 'Henrique Queiroz De Aguiar' 'Tiago Hugo Cazula Pereira'
 'Mateus Breno Prado Silva' 'Felipe Ribeiro Amorim'
 'Felipe Assis Nogueira Silva' 'Carlos Da Cunha Teixeira'
 'Breno Ribas De Moura' 'Thiago Da Cunha Teixeira'
 'Tiago Ivair De Assis Setta' 'Leticia Malaquias De Souza Oliveira'
 'Leticia Gonçalves Donadoni' 'Mateus Gonçalves Donadoni'
 'Carlos Carlos De Souza' 'Mateus Risson Euzebio'
 'Blendow Segurasse Gonçalves' 'Blendow Castilho Cardoso'
 'Matheus Henrique Caçador' 'Kallebe Vieira Demarque'
 'Samuel Picanço Santos Ferreira Silva' 'Miguel Matheus Da Silva'
 'João Castilho Cardoso' 'Tiago Carlos De Souza' 'Levi Vieira Demarque']

Valores únicos da coluna 'produto':
['Queijo Mussarela' 'Molho De Tomate' 'Água Mineral' 'Carvão' 'Café'
 'Feijão' 'Condicionador' 'Sabonete' 'Açúcar' 'Manteiga' 'Papel Higiênico'
 'Óleo De Soja' 'Vinho' 'Macarrão' 'Shampoo' 'Presunto' 'Cerveja'
 'Papel Toalha' 'Pasta De Dente' 'Pão De Forma' 'Sabão Em Pó' 'Amaciante'
 'Desinfetante' 'Refrigerante' 'Arroz' 'Farinha De Trigo'
 'Biscoito Recheado' 'Sal' 'Suco De Laranja' 'Leite Integral' 'Detergente']

Valores únicos da coluna 'status':
['Pagamento Confirmado' 'Em Separação' 'Entregue Com Sucesso'
 'Aguardando Pagamento' 'Em Transporte' 'Ap' 'Entregue' 'Pc' 'Sep'
 'Separando' 'Pgto Confirmado' 'Transp' 'Transportando' 'Entg'
 'Aguardando Pgto']

Valores únicos da coluna 'cidade':
['Niterói' 'Mariana' 'Cabo Frio' 'Campos Dos Goytacazes'
 'Conselheiro Lafaiete' 'Resende Costa' 'São Paulo' 'Bicas'
 'São João Del-Rei' 'São Gonçalo' 'São Bernardo Do Campo'
 'Duque De Caxias' 'Macaé' 'Viçosa' 'Juiz De Fora' 'Guarulhos'
 'Matias Barbosa' 'Campinas' 'Barroso' 'Carandaí' 'Barbacena' 'Itaboraí'
 'Muriaé' 'Petrópolis' 'Ouro Branco' 'Prados' 'Santos Dumont' 'Cataguases'
 'São João De Meriti' 'Ubá' 'Palma' 'Simão Pereira' 'Magé'
 'Ewbank Da Câmara' 'Santana Do Garambéu' 'Astolfo Dutra'
 'São João Nepomuceno' 'Belo Horizonte' 'Tocantins' 'Congonhas'
 'São Vicente De Minas' 'Coronel Xavier Chaves' 'Leopoldina'
 'Belford Roxo' 'Ritápolis' 'Lagoa Dourada' 'Rio De Janeiro' 'Nova Iguaçu'
 'São Tiago' 'São José Dos Campos' 'Volta Redonda' 'Lima Duarte'
 'Santo André' 'Tiradentes' 'Ouro Preto' 'Angra Dos Reis']


In [144]:
print(df['estado'].unique())

['RJ' 'MG' 'SP' 'MTSA' 'SÃO PAULO' 'RS' 'PR' 'PSC']

In [145]:
#padronizar os estados agora

mapeamento_estado = {
    'SÃO PAULO': 'SP',
    'MTSA': 'MT',   # Supondo que seja Mato Grosso
    'PSC': 'SC',    # Supondo que seja Santa Catarina
}

df['estado'] = df['estado'].replace(mapeamento_estado)

In [146]:
print(df['estado'].unique())

['RJ' 'MG' 'SP' 'MT' 'RS' 'PR' 'SC']

In [147]:
print(df['status'].unique())

['Pagamento Confirmado' 'Em Separação' 'Entregue Com Sucesso'
 'Aguardando Pagamento' 'Em Transporte' 'Ap' 'Entregue' 'Pc' 'Sep'
 'Separando' 'Pgto Confirmado' 'Transp' 'Transportando' 'Entg'
 'Aguardando Pgto']

In [148]:
mapeamento_status = {
    'Pgto Confirmado': 'Pagamento Confirmado',
    'Pagamento Confirmado': 'Pagamento Confirmado',

    'Aguardando Pgto': 'Aguardando Pagamento',
    'Aguardando Pagamento': 'Aguardando Pagamento',

    'Em Separação': 'Em Separação',
    'Sep': 'Em Separação',
    'Separando': 'Em Separação',

    'Em Transporte': 'Em Transporte',
    'Transp': 'Em Transporte',
    'Transportando': 'Em Transporte',

    'Entregue Com Sucesso': 'Entregue',
    'Entregue': 'Entregue',
    'Entg': 'Entregue',

    'Ap': 'Aguardando Pagamento',  
    'Pc': 'Pagamento Confirmado'  
}

df['status'] = df['status'].replace(mapeamento_status)

In [149]:
print(df['status'].unique())

['Pagamento Confirmado' 'Em Separação' 'Entregue' 'Aguardando Pagamento'
 'Em Transporte']

In [150]:
# Exemplo para a coluna 'valor'
Q1 = df['valor'].astype(float).quantile(0.25)
Q3 = df['valor'].astype(float).quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Filtra os outliers
outliers_valor = df[(df['valor'].astype(float) < limite_inferior) | (df['valor'].astype(float) > limite_superior)]

# Visualiza
outliers_valor[['produto', 'valor']]

#pelo visto nao temos outliers expressivos

                 produto  valor
0       Queijo Mussarela  16.87
23                 Vinho  30.35
35                 Vinho  33.33
58      Queijo Mussarela  16.45
62                 Vinho  23.89
...                  ...    ...
368588             Vinho  25.20
368605  Queijo Mussarela  16.48
368612             Vinho  35.32
368703  Queijo Mussarela  17.24
368738  Queijo Mussarela  16.62

[15458 rows x 2 columns]

In [151]:
# Salva o DataFrame como CSV na pasta 'working'
df.to_csv('/kaggle/working/vendas_limpo4.csv', index=False)

# Confirmação
print("Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv")

Arquivo exportado com sucesso para /kaggle/working/vendas_limpo.csv

In [152]:
display(df.describe(include='all'))

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,total_com_frete
count,365072.000000,365072,365072,365072,365072,365072.000000,365072.000000,365072.00000,365072,365072,365072,365072,365072,365072.000000,365072,365072,365072,365072.000000
unique,NaN,NaN,NaN,648,31,NaN,NaN,NaN,5,56,7,1,56,NaN,9,10,88,NaN
top,NaN,NaN,NaN,Victor Henrique Caçador,Pasta De Dente,NaN,NaN,NaN,Em Separação,Cabo Frio,MG,Brasil,28900-000,NaN,Cartão De Crédito,Paulo Souza Roncete,Dove,NaN
freq,NaN,NaN,NaN,2588,25982,NaN,NaN,NaN,109489,7158,226871,365072,7158,NaN,107372,36980,15071,NaN
mean,29989.524513,2020-06-16 11:46:51.430074112,1900-01-01 14:24:24.744253184,NaN,NaN,6.358473,7.186100,45.20680,NaN,NaN,NaN,NaN,NaN,63.790073,NaN,NaN,NaN,108.996873
min,0.000000,2018-01-02 00:00:00,1900-01-01 00:01:09,NaN,NaN,0.930000,1.000000,1.00000,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,9.000000
25%,14973.000000,2019-02-22 00:00:00,1900-01-01 10:51:01,NaN,NaN,2.920000,3.000000,13.16000,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,27.280000
50%,30007.000000,2020-06-22 00:00:00,1900-01-01 14:41:53,NaN,NaN,4.180000,7.000000,27.80000,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN,NaN,41.930000
75%,44971.000000,2021-09-13 00:00:00,1900-01-01 17:59:42,NaN,NaN,8.320000,11.000000,51.80000,NaN,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,67.290000
max,59999.000000,2022-12-29 00:00:00,1900-01-01 23:59:51,NaN,NaN,43.800000,24.000000,654.15000,NaN,NaN,NaN,NaN,NaN,162150.000000,NaN,NaN,NaN,162215.400000
std,17314.617204,NaN,NaN,NaN,NaN,5.466554,4.650885,56.11197,NaN,NaN,NaN,NaN,NaN,933.719673,NaN,NaN,NaN,935.465925

In [153]:
df['cliente'] = df['cliente'].str.upper()

In [154]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,total_com_frete
0,13679,2021-03-20,1900-01-01 23:35:51,LUCAS ARAUJO KUHN,Queijo Mussarela,16.87,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,239.31
1,28070,2020-10-30,1900-01-01 09:00:53,MICAEL SOUZA RONCETE,Molho De Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,21.75
2,47484,2021-06-09,1900-01-01 15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,36.67
3,20809,2022-06-04,1900-01-01 08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,54.96
4,47123,2019-05-04,1900-01-01 13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,29.46

In [155]:
df['hora'] = pd.to_datetime(df['hora'], format='%H:%M:%S').dt.strftime('%H:%M:%S')
display(df[['hora']].head())

       hora
0  23:35:51
1  09:00:53
2  15:30:28
3  08:41:23
4  13:38:45

In [156]:
#formatar a data
df['data'] = pd.to_datetime(df['data'], errors='coerce')
display(df[['data']].head())

        data
0 2021-03-20
1 2020-10-30
2 2021-06-09
3 2022-06-04
4 2019-05-04

In [157]:
#vamos averiguar os fretes
fretes_por_cidade = df.groupby('cidade')['frete'].nunique().reset_index()
fretes_com_mais_de_um_valor = fretes_por_cidade[fretes_por_cidade['frete'] > 1]

print(fretes_com_mais_de_um_valor)

                   cidade  frete
0          Angra Dos Reis      4
1           Astolfo Dutra      3
2               Barbacena      3
3                 Barroso      3
4            Belford Roxo      3
5          Belo Horizonte      4
6                   Bicas      3
7               Cabo Frio      3
8                Campinas      3
9   Campos Dos Goytacazes      3
10               Carandaí      3
11             Cataguases      4
12              Congonhas      3
13   Conselheiro Lafaiete      3
14  Coronel Xavier Chaves      3
15        Duque De Caxias      3
16       Ewbank Da Câmara      3
17              Guarulhos      3
18               Itaboraí      3
19           Juiz De Fora      4
20          Lagoa Dourada      3
21             Leopoldina      3
22            Lima Duarte      4
23                  Macaé      3
24                   Magé      3
25                Mariana      3
26         Matias Barbosa      3
27                 Muriaé      3
28                Niterói      3
29            Nova Iguaçu      3
30            Ouro Branco      4
31             Ouro Preto      3
32                  Palma      3
33             Petrópolis      3
34                 Prados      4
35          Resende Costa      3
36         Rio De Janeiro      3
37              Ritápolis      3
38    Santana Do Garambéu      4
39            Santo André      3
40          Santos Dumont      3
41          Simão Pereira      4
42  São Bernardo Do Campo      3
43            São Gonçalo      3
44    São José Dos Campos      4
45     São João De Meriti      3
46       São João Del-Rei      4
47    São João Nepomuceno      3
48              São Paulo      3
49              São Tiago      4
50   São Vicente De Minas      4
51             Tiradentes      4
52              Tocantins      4
53                    Ubá      3
54                 Viçosa      4
55          Volta Redonda      4

In [158]:
mediana_frete_por_cidade = df.groupby('cidade')['frete'].median().reset_index()
mediana_frete_por_cidade.columns = ['cidade', 'mediana_frete']
print(mediana_frete_por_cidade)

                   cidade  mediana_frete
0          Angra Dos Reis           23.0
1           Astolfo Dutra           10.0
2               Barbacena           12.0
3                 Barroso            8.5
4            Belford Roxo           19.0
5          Belo Horizonte           10.0
6                   Bicas            9.0
7               Cabo Frio           22.0
8                Campinas           17.0
9   Campos Dos Goytacazes           20.0
10               Carandaí            9.0
11             Cataguases           10.5
12              Congonhas           10.5
13   Conselheiro Lafaiete           10.5
14  Coronel Xavier Chaves           11.0
15        Duque De Caxias           19.0
16       Ewbank Da Câmara           11.0
17              Guarulhos           18.0
18               Itaboraí           18.5
19           Juiz De Fora           13.0
20          Lagoa Dourada           10.0
21             Leopoldina            9.5
22            Lima Duarte           10.0
23                  Macaé           20.0
24                   Magé           18.0
25                Mariana           12.0
26         Matias Barbosa           10.0
27                 Muriaé           10.0
28                Niterói           20.0
29            Nova Iguaçu           18.0
30            Ouro Branco           10.0
31             Ouro Preto           12.5
32                  Palma            9.0
33             Petrópolis           21.0
34                 Prados            8.0
35          Resende Costa           10.0
36         Rio De Janeiro           22.0
37              Ritápolis            9.0
38    Santana Do Garambéu            8.5
39            Santo André           18.0
40          Santos Dumont           11.0
41          Simão Pereira            9.5
42  São Bernardo Do Campo           18.0
43            São Gonçalo           20.0
44    São José Dos Campos           17.0
45     São João De Meriti           18.0
46       São João Del-Rei           10.5
47    São João Nepomuceno           12.0
48              São Paulo           20.0
49              São Tiago            9.5
50   São Vicente De Minas           12.0
51             Tiradentes           10.0
52              Tocantins            8.5
53                    Ubá           11.0
54                 Viçosa            9.0
55          Volta Redonda           19.0

In [159]:
# Primeiro, calcular a mediana por cidade
mediana_frete_por_cidade = df.groupby('cidade')['frete'].median().to_dict()

# Agora, criar uma função que aplica a mediana se o frete for nulo ou inválido
def substituir_frete(row):
    if pd.isnull(row['frete']) or row['frete'] <= 0:
        return mediana_frete_por_cidade.get(row['cidade'], row['frete'])  # se não encontrar, mantém original
    return row['frete']

# Aplicar ao DataFrame
df['frete'] = df.apply(substituir_frete, axis=1)

In [160]:
#vamos averiguar os fretes
fretes_por_cidade = df.groupby('cidade')['frete'].nunique().reset_index()
fretes_com_mais_de_um_valor = fretes_por_cidade[fretes_por_cidade['frete'] > 1]

print(fretes_com_mais_de_um_valor)

                   cidade  frete
0          Angra Dos Reis      4
1           Astolfo Dutra      3
2               Barbacena      3
3                 Barroso      3
4            Belford Roxo      3
5          Belo Horizonte      4
6                   Bicas      3
7               Cabo Frio      3
8                Campinas      3
9   Campos Dos Goytacazes      3
10               Carandaí      3
11             Cataguases      4
12              Congonhas      3
13   Conselheiro Lafaiete      3
14  Coronel Xavier Chaves      3
15        Duque De Caxias      3
16       Ewbank Da Câmara      3
17              Guarulhos      3
18               Itaboraí      3
19           Juiz De Fora      4
20          Lagoa Dourada      3
21             Leopoldina      3
22            Lima Duarte      4
23                  Macaé      3
24                   Magé      3
25                Mariana      3
26         Matias Barbosa      3
27                 Muriaé      3
28                Niterói      3
29            Nova Iguaçu      3
30            Ouro Branco      4
31             Ouro Preto      3
32                  Palma      3
33             Petrópolis      3
34                 Prados      4
35          Resende Costa      3
36         Rio De Janeiro      3
37              Ritápolis      3
38    Santana Do Garambéu      4
39            Santo André      3
40          Santos Dumont      3
41          Simão Pereira      4
42  São Bernardo Do Campo      3
43            São Gonçalo      3
44    São José Dos Campos      4
45     São João De Meriti      3
46       São João Del-Rei      4
47    São João Nepomuceno      3
48              São Paulo      3
49              São Tiago      4
50   São Vicente De Minas      4
51             Tiradentes      4
52              Tocantins      4
53                    Ubá      3
54                 Viçosa      4
55          Volta Redonda      4

In [161]:
# Calcular a mediana do frete por cidade
mediana_frete_por_cidade = df.groupby('cidade')['frete'].median().to_dict()

# Substituir todos os fretes pelo valor da mediana correspondente da cidade
df['frete'] = df['cidade'].map(mediana_frete_por_cidade)

In [162]:
#vamos averiguar os fretes
fretes_por_cidade = df.groupby('cidade')['frete'].nunique().reset_index()
fretes_com_mais_de_um_valor = fretes_por_cidade[fretes_por_cidade['frete'] > 1]

print(fretes_com_mais_de_um_valor)

Empty DataFrame
Columns: [cidade, frete]
Index: []

In [163]:
print(df['frete'])

0         20.0
1         12.0
2         22.0
3         20.0
4         10.5
          ...
368747    19.0
368748    20.0
368749    18.0
368750    19.0
368751    18.0
Name: frete, Length: 365072, dtype: float64

In [164]:

#verificar agora os produtos
# Calcular média e desvio padrão por produto e marca
media_desvio = df.groupby(['produto', 'marca'])['valor'].agg(['mean', 'std']).reset_index()

# Renomear as colunas para evitar erro de KeyError
media_desvio.rename(columns={'mean': 'media', 'std': 'desvio'}, inplace=True)

# Mesclar as estatísticas no DataFrame original
df = df.merge(media_desvio, on=['produto', 'marca'], how='left')

# Identificar outliers (valores fora de 3 desvios padrão da média)
df['outlier'] = (df['valor'] > (df['media'] + 3 * df['desvio'])) | (df['valor'] < (df['media'] - 3 * df['desvio']))

# Substituir os outliers pelo valor médio do mesmo produto e marca
df.loc[df['outlier'], 'valor'] = df.loc[df['outlier'], 'media']

# Remover colunas auxiliares
df = df.drop(columns=['media', 'desvio', 'outlier'])

# Exibir o DataFrame atualizado
print(df)

        id_da_compra       data      hora                            cliente  \
0              13679 2021-03-20  23:35:51                  LUCAS ARAUJO KUHN
1              28070 2020-10-30  09:00:53               MICAEL SOUZA RONCETE
2              47484 2021-06-09  15:30:28          FELIPE AUGUSTO NERY SILVA
3              20809 2022-06-04  08:41:23                LEVI RIBEIRO AMORIM
4              47123 2019-05-04  13:38:45        GABRIEL MATOS LIMA DA CUNHA
...              ...        ...       ...                                ...
365067         43399 2018-11-02  23:00:58           PEDRO GONÇALVES DONADONI
365068         18398 2022-08-13  12:46:43               PEDRO MURATORI DUTRA
365069         12169 2021-02-23  19:09:58         TIAGO IVAIR DE ASSIS SETTA
365070         16921 2020-04-25  06:59:09           SAMUEL JOSÉ SILVA MATIAS
365071         11240 2018-03-22  22:47:21  LUCAS MALAQUIAS DE SOUZA OLIVEIRA

                 produto  valor  quantidade  total_sem_frete  \
0       Queijo Mussarela  16.87          13           219.31
1        Molho De Tomate   3.25           3             9.75
2           Água Mineral   1.63           9            14.67
3                 Carvão   8.74           4            34.96
4                   Café   9.48           2            18.96
...                  ...    ...         ...              ...
365067      Água Mineral   1.43          14            20.02
365068      Refrigerante   5.01           4            20.04
365069          Presunto  11.01           7            77.07
365070             Arroz   4.56           3            13.68
365071      Papel Toalha   3.17           6            19.02

                      status                 cidade estado    pais        cep  \
0       Pagamento Confirmado                Niterói     RJ  Brasil  24000-000
1       Pagamento Confirmado                Mariana     MG  Brasil  35420-000
2       Pagamento Confirmado              Cabo Frio     RJ  Brasil  28900-000
3               Em Separação  Campos Dos Goytacazes     RJ  Brasil  28000-000
4               Em Separação   Conselheiro Lafaiete     MG  Brasil  36400-000
...                      ...                    ...    ...     ...        ...
365067              Entregue           Belford Roxo     RJ  Brasil  26100-000
365068  Aguardando Pagamento            São Gonçalo     RJ  Brasil  24400-000
365069              Entregue            Santo André     SP  Brasil  09000-000
365070  Pagamento Confirmado          Volta Redonda     RJ  Brasil  27200-000
365071  Aguardando Pagamento            Santo André     SP  Brasil  09000-000

        frete               pagamento                            vendedor  \
0        20.0       Cartão De Crédito             Samuel Henrique Caçador
1        12.0                     Pix  Micael Malaquias De Souza Oliveira
2        22.0  Transferência Bancária         Henrico Matos Lima Da Cunha
3        20.0                     Pix           Gabriel Queiroz De Aguiar
4        10.5       Cartão De Crédito         Henrico Matos Lima Da Cunha
...       ...                     ...                                 ...
365067   19.0  Transferência Bancária            Carlos Queiroz De Aguiar
365068   20.0                     Pix                 Paulo Souza Roncete
365069   18.0  Transferência Bancária         Henrico Matos Lima Da Cunha
365070   19.0  Transferência Bancária           Gabriel Queiroz De Aguiar
365071   18.0       Cartão De Crédito                Henrico Victor Alves

                    marca  total_com_frete
0            Porto Alegre           239.31
1                  Fugini            21.75
2                 Minalba            36.67
3              Marca-Brás            54.96
4              3 Corações            29.46
...                   ...              ...
365067            Minalba            39.02
365068  Guaraná Antártica            40.04
365069           Perdigão            95.07
365070              Camil            32.68
365071               Snob            37.02

[365072 rows x 18 columns]

In [165]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,total_com_frete
0,13679,2021-03-20,23:35:51,LUCAS ARAUJO KUHN,Queijo Mussarela,16.87,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,239.31
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho De Tomate,3.25,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,21.75
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,1.63,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,36.67
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.74,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,54.96
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,9.48,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,29.46

In [166]:
#verificando o nulo
df['vendedor'].isnull().sum()

0

In [167]:
#tratar os valores de cada produto por marca
mediana_valor_por_marca = df.groupby('marca')['valor'].median()
print(mediana_valor_por_marca)

marca
3 Corações    10.01
Adria          3.03
Anaconda       3.02
Aurora        10.02
Aviação        8.03
              ...
União          3.01
Urbano         5.02
Veja           5.04
Wickbold       5.98
Ypê            3.02
Name: valor, Length: 88, dtype: float64

In [168]:
# Substitui o valor de cada produto pela mediana de sua marca
df['valor'] = df['marca'].map(mediana_valor_por_marca)

In [169]:
# Salva o DataFrame como CSV na pasta de trabalho do Kaggle
df.to_csv('/kaggle/working/vendas_atualizado.csv', index=False)

print("Arquivo salvo com sucesso em /kaggle/working/vendas_atualizado.csv")

Arquivo salvo com sucesso em /kaggle/working/vendas_atualizado.csv

In [170]:
df['valor'] = df.groupby(['produto', 'marca'])['valor'].transform(lambda x: x.fillna(x.mean()))

In [171]:
df.loc[df['total_sem_frete'].isnull(), 'total_sem_frete'] = df['quantidade'] * df['valor']

In [172]:
df.loc[df['total_sem_frete'].isnull(), 'total_sem_frete'] = df['quantidade'] * df['valor']

In [173]:
duplicadas = df.duplicated(subset=['id_da_compra','produto', 'marca'])
print(duplicadas.sum())  # Mostra quantas duplicatas existem considerando apenas essas colunas

33557

In [174]:
df.head()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total_sem_frete,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,total_com_frete
0,13679,2021-03-20,23:35:51,LUCAS ARAUJO KUHN,Queijo Mussarela,15.05,13,219.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão De Crédito,Samuel Henrique Caçador,Porto Alegre,239.31
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho De Tomate,4.01,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,12.0,Pix,Micael Malaquias De Souza Oliveira,Fugini,21.75
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,2.01,9,14.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,Henrico Matos Lima Da Cunha,Minalba,36.67
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,8.00,4,34.96,Em Separação,Campos Dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,Gabriel Queiroz De Aguiar,Marca-Brás,54.96
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,10.01,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,10.5,Cartão De Crédito,Henrico Matos Lima Da Cunha,3 Corações,29.46

In [175]:
df = df.groupby(
    ['id_da_compra','data','hora','cliente','produto','valor','quantidade','total_com_frete','status','cidade','estado','pais','cep','frete','pagamento','vendedor','marca','total_sem_frete'], 
    as_index=False
).agg({'quantidade': 'sum','valor': 'first','total_sem_frete': 'first','total_com_frete': 'first'})

In [176]:
df.to_csv('/kaggle/working/vendas_modificado5.csv', index=False)
print("Arquivo CSV salvo com sucesso na pasta working!")

Arquivo CSV salvo com sucesso na pasta working!

In [177]:
print(df['data'].dtype)

datetime64[ns]

In [178]:
#deixar os nomes dos vendedores em maiusculas iguais dos clientes:

df['vendedor'] = df['vendedor'].str.upper()

In [179]:
df.head(
    
)

,id_da_compra,data,hora,cliente,produto,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,quantidade,valor,total_sem_frete,total_com_frete
0,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,Macarrão,Aguardando Pagamento,Ouro Branco,MG,Brasil,36420-000,10.0,Cartão De Crédito,VICTOR GONÇALVES DONADONI,Renata,14,2.98,36.82,46.82
1,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,Pasta De Dente,Aguardando Pagamento,Ouro Branco,MG,Brasil,36420-000,10.0,Cartão De Crédito,VICTOR GONÇALVES DONADONI,Colgate,9,3.01,26.82,36.82
2,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,Sabonete,Aguardando Pagamento,Ouro Branco,MG,Brasil,36420-000,10.0,Cartão De Crédito,VICTOR GONÇALVES DONADONI,Lux,7,2.00,14.00,24.00
3,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,Sabonete,Aguardando Pagamento,Ouro Branco,MG,Brasil,36420-000,10.0,Cartão De Crédito,VICTOR GONÇALVES DONADONI,Nivea,15,2.02,36.00,46.00
4,1,2018-08-23,17:52:53,PEDRO DA SILVA BIANQUINI,Detergente,Pagamento Confirmado,Duque De Caxias,RJ,Brasil,25000-000,19.0,Cartão De Crédito,HENRICO VICTOR ALVES,Minuano,15,3.02,51.75,70.75

In [180]:
#converter todas as coluans para capslock tornando um padrao
colunas_para_maiusculas = ['produto', 'status', 'cidade', 'pais', 'pagamento', 'marca']
for coluna in colunas_para_maiusculas:
    df[coluna] = df[coluna].str.upper()

In [181]:
df.head()

,id_da_compra,data,hora,cliente,produto,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,quantidade,valor,total_sem_frete,total_com_frete
0,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,MACARRÃO,AGUARDANDO PAGAMENTO,OURO BRANCO,MG,BRASIL,36420-000,10.0,CARTÃO DE CRÉDITO,VICTOR GONÇALVES DONADONI,RENATA,14,2.98,36.82,46.82
1,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,PASTA DE DENTE,AGUARDANDO PAGAMENTO,OURO BRANCO,MG,BRASIL,36420-000,10.0,CARTÃO DE CRÉDITO,VICTOR GONÇALVES DONADONI,COLGATE,9,3.01,26.82,36.82
2,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,SABONETE,AGUARDANDO PAGAMENTO,OURO BRANCO,MG,BRASIL,36420-000,10.0,CARTÃO DE CRÉDITO,VICTOR GONÇALVES DONADONI,LUX,7,2.00,14.00,24.00
3,0,2019-07-07,11:05:44,PEDRO SILVA RAMOS,SABONETE,AGUARDANDO PAGAMENTO,OURO BRANCO,MG,BRASIL,36420-000,10.0,CARTÃO DE CRÉDITO,VICTOR GONÇALVES DONADONI,NIVEA,15,2.02,36.00,46.00
4,1,2018-08-23,17:52:53,PEDRO DA SILVA BIANQUINI,DETERGENTE,PAGAMENTO CONFIRMADO,DUQUE DE CAXIAS,RJ,BRASIL,25000-000,19.0,CARTÃO DE CRÉDITO,HENRICO VICTOR ALVES,MINUANO,15,3.02,51.75,70.75

In [182]:
output_path = "/kaggle/working/df_modificado.csv"
df.to_csv(output_path, index=False)

# Mensagem confirmando que o arquivo foi salvo
print(f"\n📁 Arquivo 'df_modificado.csv' salvo com sucesso em {output_path}!")

📁 Arquivo 'df_modificado.csv' salvo com sucesso em /kaggle/working/df_modificado.csv!